void target_incrementor();
void load_map(char mapnumber);
void setup_game();
void initiate_level(int mapnumber);
void initialize_wall(int framex, int framey, int type, int w, int h, int x, int y);
void initialize_sprite(int type, int x_postion, int y_position,  char direction, int time);
void animation(int sprite_number);
void die();
void destroysprite(int spritee);
void destroysprite();
void destroywall();
void sprite_update(int spriten);
int check_colision(int sprite_number, int loop, int sop);
void sprite_colision(int sprite_number, int type);
void damage(int howmuch);
void player_colision();
void enemy_ai(int type, int sprite_number);
void input();
void move_player(float x_amount, float y_amount);
void draw();
void set_dvalues(int number);
void callevent(int event_number);
void run_scripts();
