/* Allegro datafile object indexes, produced by grabber v4.1.17 (WIP), MinGW32 */
/* Datafile: c:\Documents and Settings\Doft ViD4 l0k4\Desktop\Lucas\Joguito\files.dat */
/* Date: Tue May 20 17:18:51 2008 */
/* Do not hand edit! */

#define AAA                              0        /* BMP  */
#define ACCEPT                           1        /* SAMP */
#define AGUA                             2        /* BMP  */
#define AGUAT1                           3        /* BMP  */
#define AGUAT2                           4        /* BMP  */
#define AGUAT3                           5        /* BMP  */
#define ANIM13                           6        /* SAMP */
#define ANIM40                           7        /* SAMP */
#define ANIM60                           8        /* SAMP */
#define ARMOREYES1                       9        /* BMP  */
#define ARMOREYES2                       10       /* BMP  */
#define ARMOREYES3                       11       /* BMP  */
#define ARMOREYES4                       12       /* BMP  */
#define ARROW                            13       /* BMP  */
#define ASINHAKAWAII                     14       /* BMP  */
#define BACULO                           15       /* BMP  */
#define BG1                              16       /* BMP  */
#define BG2                              17       /* BMP  */
#define BG3                              18       /* BMP  */
#define BG4                              19       /* BMP  */
#define BG5                              20       /* BMP  */
#define BG6                              21       /* BMP  */
#define BG7                              22       /* BMP  */
#define BG8                              23       /* BMP  */
#define BGM1                             24       /* MIDI */
#define BGM2                             25       /* MIDI */
#define BGM3                             26       /* MIDI */
#define BGM4                             27       /* MIDI */
#define BGM5                             28       /* MIDI */
#define BGM6                             29       /* MIDI */
#define BGM7                             30       /* MIDI */
#define BGM8                             31       /* MIDI */
#define BGM9                             32       /* MIDI */
#define BGMA                             33       /* MIDI */
#define BGMB                             34       /* MIDI */
#define BIG                              35       /* BMP  */
#define BIGTHUNDER                       36       /* SAMP */
#define BIRD1                            37       /* BMP  */
#define BIRD2                            38       /* BMP  */
#define BIRD3                            39       /* BMP  */
#define BIRDFLY1                         40       /* BMP  */
#define BIRDFLY2                         41       /* BMP  */
#define BIRDSTAND                        42       /* BMP  */
#define BIRDSTAND1                       43       /* BMP  */
#define BIRDSTAND2                       44       /* BMP  */
#define BIRDSTAND3                       45       /* BMP  */
#define BLOCK                            46       /* BMP  */
#define BOLHAS                           47       /* BMP  */
#define BOULDERLOL                       48       /* BMP  */
#define BUBBLES                          49       /* BMP  */
#define CARD01                           50       /* BMP  */
#define CARD02                           51       /* BMP  */
#define CARD03                           52       /* BMP  */
#define CARD04                           53       /* BMP  */
#define CARD05                           54       /* BMP  */
#define CARDBACK1                        55       /* BMP  */
#define CARDBACK2                        56       /* BMP  */
#define CARDBACK3                        57       /* BMP  */
#define CARDGET                          58       /* SAMP */
#define CARDHOLDER                       59       /* BMP  */
#define CARDHOLDER2                      60       /* BMP  */
#define CHANGE                           61       /* BMP  */
#define CHEAT                            62       /* BMP  */
#define CLOUD                            63       /* BMP  */
#define CREATE                           64       /* BMP  */
#define CREDITS1                         65       /* BMP  */
#define CREDITS2                         66       /* BMP  */
#define CREDITS3                         67       /* BMP  */
#define CREDITS4                         68       /* BMP  */
#define CREDITS5                         69       /* BMP  */
#define CREDITS6                         70       /* BMP  */
#define CSELECT                          71       /* BMP  */
#define DA400                            72       /* BMP  */
#define DA401                            73       /* BMP  */
#define DA402                            74       /* BMP  */
#define DA600                            75       /* BMP  */
#define DA601                            76       /* BMP  */
#define DA602                            77       /* BMP  */
#define DARK                             78       /* BMP  */
#define DASH                             79       /* BMP  */
#define DENY                             80       /* SAMP */
#define DESTROYABLEPAREDE                81       /* BMP  */
#define DESTROYABLEPAREDE2               82       /* BMP  */
#define DIE                              83       /* SAMP */
#define DREAM                            84       /* BMP  */
#define EARTHY                           85       /* BMP  */
#define ENDING1                          86       /* BMP  */
#define ENDING2                          87       /* BMP  */
#define ENDING3                          88       /* BMP  */
#define ENDING4                          89       /* BMP  */
#define ENDING5                          90       /* BMP  */
#define ENDING6                          91       /* BMP  */
#define ENDINGFONT                       92       /* FONT */
#define ERASE                            93       /* BMP  */
#define EWUL_SQUID01                     94       /* BMP  */
#define EWUL_SQUID02                     95       /* BMP  */
#define EWUL_SQUID03                     96       /* BMP  */
#define EWUL_SQUID04                     97       /* BMP  */
#define EWUL_SQUID05                     98       /* BMP  */
#define EWUL_SQUID06                     99       /* BMP  */
#define EWULARMOR1                       100      /* BMP  */
#define EWULARMOR2                       101      /* BMP  */
#define EWULFISH_11                      102      /* BMP  */
#define EWULFISH_12                      103      /* BMP  */
#define EWULFISH_13                      104      /* BMP  */
#define EWULFISH_21                      105      /* BMP  */
#define EWULFISH_22                      106      /* BMP  */
#define EWULFISH_23                      107      /* BMP  */
#define EWULFISH_31                      108      /* BMP  */
#define EWULFISH_32                      109      /* BMP  */
#define EWULFISH_33                      110      /* BMP  */
#define EWULFISH_41                      111      /* BMP  */
#define EWULFISH_42                      112      /* BMP  */
#define EWULFISH_43                      113      /* BMP  */
#define EWULINSETO                       114      /* BMP  */
#define EWULMACHINE01                    115      /* BMP  */
#define EWULMISSILE                      116      /* SAMP */
#define EWULMISSILE01                    117      /* BMP  */
#define EWULOSTRABALLB                   118      /* BMP  */
#define EWULOSTRABALLW                   119      /* BMP  */
#define EWULOSTRAPT1                     120      /* BMP  */
#define EWULOSTRAPT2                     121      /* BMP  */
#define EWULOSTRAPT3                     122      /* BMP  */
#define EWULOSTRAPT4                     123      /* BMP  */
#define EXIT                             124      /* BMP  */
#define FIGHT                            125      /* BMP  */
#define FIRE1                            126      /* BMP  */
#define FIRE2                            127      /* BMP  */
#define FIRE3                            128      /* BMP  */
#define FIRE4                            129      /* BMP  */
#define FIRE5                            130      /* BMP  */
#define FIRE6                            131      /* BMP  */
#define FIRE7                            132      /* BMP  */
#define FIRESLASH                        133      /* SAMP */
#define FIREY                            134      /* BMP  */
#define FIREYFLAME                       135      /* SAMP */
#define FLAMEMET1                        136      /* BMP  */
#define FLAMEMET2                        137      /* BMP  */
#define FLAMEMET3                        138      /* BMP  */
#define FLAMEMET4                        139      /* BMP  */
#define FLAMES01                         140      /* BMP  */
#define FLAMES02                         141      /* BMP  */
#define FLAMES03                         142      /* BMP  */
#define FLAMES04                         143      /* BMP  */
#define FLAMES05                         144      /* BMP  */
#define FLAMES06                         145      /* BMP  */
#define FLAMES07                         146      /* BMP  */
#define FLAMES08                         147      /* BMP  */
#define FLAMES09                         148      /* BMP  */
#define FLAMES11                         149      /* BMP  */
#define FLAMES12                         150      /* BMP  */
#define FLAMES13                         151      /* BMP  */
#define FLAMES14                         152      /* BMP  */
#define FLAMES15                         153      /* BMP  */
#define FLAMES16                         154      /* BMP  */
#define FLAMES17                         155      /* BMP  */
#define FLAMES18                         156      /* BMP  */
#define FLAMES19                         157      /* BMP  */
#define FLAMETHROWER                     158      /* SAMP */
#define FLAMETHROWER1                    159      /* BMP  */
#define FLAMETHROWER2                    160      /* BMP  */
#define FLOAT                            161      /* BMP  */
#define FLOWER                           162      /* BMP  */
#define FLY                              163      /* BMP  */
#define FREEZE                           164      /* BMP  */
#define GHOST01                          165      /* BMP  */
#define GHOST02                          166      /* BMP  */
#define GHOST03                          167      /* BMP  */
#define GHOST04                          168      /* BMP  */
#define GHOSTMASK01                      169      /* BMP  */
#define GHOSTMASK02                      170      /* BMP  */
#define GHOSTMASK03                      171      /* BMP  */
#define GLASS                            172      /* SAMP */
#define GLOW                             173      /* BMP  */
#define GREEN_TURRET                     174      /* BMP  */
#define GUILHOTINA                       175      /* BMP  */
#define HA                               176      /* BMP  */
#define HADOUKEN01                       177      /* BMP  */
#define HADOUKEN02                       178      /* BMP  */
#define HADOUKEN03                       179      /* BMP  */
#define HADOUKEN04                       180      /* BMP  */
#define HADOUKEN05                       181      /* BMP  */
#define HADOUKEN06                       182      /* BMP  */
#define HADOUKEN07                       183      /* BMP  */
#define HADUEX                           184      /* SAMP */
#define ICE01                            185      /* BMP  */
#define ICE02                            186      /* BMP  */
#define ICEANIM                          187      /* SAMP */
#define ICEBLOCK1                        188      /* BMP  */
#define ICEBLOCK2                        189      /* BMP  */
#define ICEDESTROY                       190      /* BMP  */
#define ICEFALL                          191      /* SAMP */
#define ICEHOLDER1                       192      /* BMP  */
#define ICEHOLDER2                       193      /* BMP  */
#define ICEHOLDER3                       194      /* BMP  */
#define ICEHOLDER4                       195      /* BMP  */
#define ICEMET01                         196      /* BMP  */
#define ICEMET02                         197      /* BMP  */
#define ICEMET03                         198      /* BMP  */
#define ICEMET04                         199      /* BMP  */
#define ICENEEDLE01                      200      /* BMP  */
#define ICENEEDLE02                      201      /* BMP  */
#define ICENEEDLE03                      202      /* BMP  */
#define ICENEEDLE04                      203      /* BMP  */
#define ICESPIKE                         204      /* BMP  */
#define ICETOP                           205      /* BMP  */
#define ICETOP2                          206      /* BMP  */
#define ICYATTACK01                      207      /* BMP  */
#define ICYATTACK02                      208      /* BMP  */
#define ICYATTACK03                      209      /* BMP  */
#define ICYATTACK04                      210      /* BMP  */
#define ICYATTACK05                      211      /* BMP  */
#define ICYATTACK06                      212      /* BMP  */
#define ICYSHADOW01                      213      /* BMP  */
#define ICYSHADOW02                      214      /* BMP  */
#define ICYSHADOW03                      215      /* BMP  */
#define ICYSHADOW04                      216      /* BMP  */
#define ICYSIDE01                        217      /* BMP  */
#define ICYSIDE02                        218      /* BMP  */
#define ICYSIDE03                        219      /* BMP  */
#define ICYSIDE04                        220      /* BMP  */
#define ICYUP01                          221      /* BMP  */
#define ICYUP02                          222      /* BMP  */
#define ICYUP03                          223      /* BMP  */
#define ILLUSION                         224      /* BMP  */
#define INIMIGODUMAL                     225      /* BMP  */
#define INTRO                            226      /* MIDI */
#define INTRO0                           227      /* BMP  */
#define INTRO1                           228      /* BMP  */
#define INTRO2                           229      /* BMP  */
#define INTRO3                           230      /* BMP  */
#define INTRO4                           231      /* BMP  */
#define INTRO5                           232      /* BMP  */
#define INTROA                           233      /* BMP  */
#define IRON_DOOR                        234      /* BMP  */
#define JUMP                             235      /* BMP  */
#define LASTBALL1                        236      /* BMP  */
#define LASTBALL2                        237      /* BMP  */
#define LASTBALL3                        238      /* BMP  */
#define LASTBALL4                        239      /* BMP  */
#define LASTBOSS                         240      /* BMP  */
#define LASTS                            241      /* SAMP */
#define LASTSMALL1                       242      /* BMP  */
#define LASTSMALL2                       243      /* BMP  */
#define LASTSMALL3                       244      /* BMP  */
#define LASTSMALL4                       245      /* BMP  */
#define LAVA1                            246      /* BMP  */
#define LAVA2                            247      /* BMP  */
#define LAVA3                            248      /* BMP  */
#define LIBRA                            249      /* BMP  */
#define LIFEBAR                          250      /* BMP  */
#define LIFEMETER                        251      /* BMP  */
#define LIFEMETER2                       252      /* BMP  */
#define LIFEMETERBOSS                    253      /* BMP  */
#define LIGHT                            254      /* BMP  */
#define LITTLE                           255      /* BMP  */
#define LOAD1                            256      /* BMP  */
#define LOAD2                            257      /* BMP  */
#define LOAD3                            258      /* BMP  */
#define LOAD4                            259      /* BMP  */
#define LOCK                             260      /* BMP  */
#define LOOP                             261      /* BMP  */
#define LUZ                              262      /* BMP  */
#define MAINMENU                         263      /* BMP  */
#define MAZE                             264      /* BMP  */
#define MENU                             265      /* BMP  */
#define MENU_EX2                         266      /* BMP  */
#define MENU_FI                          267      /* BMP  */
#define MENU_FI2                         268      /* BMP  */
#define MENU_FR                          269      /* BMP  */
#define MENU_FR2                         270      /* BMP  */
#define MENU_MA2                         271      /* BMP  */
#define MENU_SH                          272      /* BMP  */
#define MENU_SH2                         273      /* BMP  */
#define MENU_TH                          274      /* BMP  */
#define MENU_TH2                         275      /* BMP  */
#define MENU_WA                          276      /* BMP  */
#define MENU_WA2                         277      /* BMP  */
#define MENU_WI                          278      /* BMP  */
#define MENU_WI2                         279      /* BMP  */
#define MENUBACK                         280      /* BMP  */
#define MENUOPTIONS                      281      /* BMP  */
#define MENUWINDOW                       282      /* BMP  */
#define MENUWINDOW2                      283      /* BMP  */
#define MENUWINDY                        284      /* BMP  */
#define MIRROR                           285      /* BMP  */
#define MIST                             286      /* BMP  */
#define MOLA_FELIZ                       287      /* BMP  */
#define MOLA_FELIZ2                      288      /* BMP  */
#define MOVE                             289      /* BMP  */
#define NEWGAME1                         290      /* BMP  */
#define NEWGAME2                         291      /* BMP  */
#define NEWGAME3                         292      /* BMP  */
#define NEWGAME4                         293      /* BMP  */
#define NULO                             294      /* BMP  */
#define OPTIONS                          295      /* BMP  */
#define OPTIONS1                         296      /* BMP  */
#define OPTIONS2                         297      /* BMP  */
#define OPTIONS3                         298      /* BMP  */
#define OPTIONS4                         299      /* BMP  */
#define ORANGE01                         300      /* BMP  */
#define ORANGE02                         301      /* BMP  */
#define ORANGE03                         302      /* BMP  */
#define ORANGE04                         303      /* BMP  */
#define ORANGE05                         304      /* BMP  */
#define ORANGE06                         305      /* BMP  */
#define ORANGE07                         306      /* BMP  */
#define ORANGE08                         307      /* BMP  */
#define ORANGE09                         308      /* BMP  */
#define ORANGEH01                        309      /* BMP  */
#define ORANGEH02                        310      /* BMP  */
#define ORANGEH03                        311      /* BMP  */
#define PAINTING1                        312      /* BMP  */
#define PAINTING2                        313      /* BMP  */
#define PARTICLEDESTROY1                 314      /* BMP  */
#define PARTICLEDESTROY2                 315      /* BMP  */
#define PARTICLES01                      316      /* BMP  */
#define PARTICLES02                      317      /* BMP  */
#define PARTICLES03                      318      /* BMP  */
#define PARTICLES04                      319      /* BMP  */
#define PDIE1                            320      /* BMP  */
#define PDIE2                            321      /* BMP  */
#define PDIE3                            322      /* BMP  */
#define PDIE4                            323      /* BMP  */
#define PDIE5                            324      /* BMP  */
#define PENA                             325      /* BMP  */
#define PENASOUND                        326      /* SAMP */
#define PIRIKITO                         327      /* BMP  */
#define PIRIKITO2                        328      /* BMP  */
#define PIRIKITO3                        329      /* BMP  */
#define PISK1                            330      /* BMP  */
#define PISK2                            331      /* BMP  */
#define PLAYER_MOVING01                  332      /* BMP  */
#define PLAYER_MOVING01A                 333      /* BMP  */
#define PLAYER_MOVING01B                 334      /* BMP  */
#define PLAYER_MOVING01C                 335      /* BMP  */
#define PLAYER_MOVING01D                 336      /* BMP  */
#define PLAYER_MOVING01E                 337      /* BMP  */
#define PLAYER_MOVING01F                 338      /* BMP  */
#define PLAYER_MOVING02                  339      /* BMP  */
#define PLAYER_MOVING02A                 340      /* BMP  */
#define PLAYER_MOVING02B                 341      /* BMP  */
#define PLAYER_MOVING02C                 342      /* BMP  */
#define PLAYER_MOVING02D                 343      /* BMP  */
#define PLAYER_MOVING02E                 344      /* BMP  */
#define PLAYER_MOVING02F                 345      /* BMP  */
#define PLAYER_MOVING03                  346      /* BMP  */
#define PLAYER_MOVING03A                 347      /* BMP  */
#define PLAYER_MOVING03B                 348      /* BMP  */
#define PLAYER_MOVING03C                 349      /* BMP  */
#define PLAYER_MOVING03D                 350      /* BMP  */
#define PLAYER_MOVING03E                 351      /* BMP  */
#define PLAYER_MOVING03F                 352      /* BMP  */
#define PLAYER_MOVING04                  353      /* BMP  */
#define PLAYER_MOVING04A                 354      /* BMP  */
#define PLAYER_MOVING04B                 355      /* BMP  */
#define PLAYER_MOVING04C                 356      /* BMP  */
#define PLAYER_MOVING04D                 357      /* BMP  */
#define PLAYER_MOVING04E                 358      /* BMP  */
#define PLAYER_MOVING04F                 359      /* BMP  */
#define PLAYER_MOVING05                  360      /* BMP  */
#define PLAYER_MOVING05A                 361      /* BMP  */
#define PLAYER_MOVING05B                 362      /* BMP  */
#define PLAYER_MOVING05C                 363      /* BMP  */
#define PLAYER_MOVING05D                 364      /* BMP  */
#define PLAYER_MOVING05E                 365      /* BMP  */
#define PLAYER_MOVING05F                 366      /* BMP  */
#define PLAYER_MOVING12                  367      /* BMP  */
#define PLAYER_MOVING12A                 368      /* BMP  */
#define PLAYER_MOVING12B                 369      /* BMP  */
#define PLAYER_MOVING12C                 370      /* BMP  */
#define PLAYER_MOVING12D                 371      /* BMP  */
#define PLAYER_MOVING12E                 372      /* BMP  */
#define PLAYER_MOVING12F                 373      /* BMP  */
#define PLAYER_MOVING22                  374      /* BMP  */
#define PLAYER_MOVING22A                 375      /* BMP  */
#define PLAYER_MOVING22B                 376      /* BMP  */
#define PLAYER_MOVING22C                 377      /* BMP  */
#define PLAYER_MOVING22D                 378      /* BMP  */
#define PLAYER_MOVING22E                 379      /* BMP  */
#define PLAYER_MOVING22F                 380      /* BMP  */
#define PLAYER_MOVING32                  381      /* BMP  */
#define PLAYER_MOVING32A                 382      /* BMP  */
#define PLAYER_MOVING32B                 383      /* BMP  */
#define PLAYER_MOVING32C                 384      /* BMP  */
#define PLAYER_MOVING32D                 385      /* BMP  */
#define PLAYER_MOVING32E                 386      /* BMP  */
#define PLAYER_MOVING32F                 387      /* BMP  */
#define PLAYER_MOVING42                  388      /* BMP  */
#define PLAYER_MOVING42A                 389      /* BMP  */
#define PLAYER_MOVING42B                 390      /* BMP  */
#define PLAYER_MOVING42C                 391      /* BMP  */
#define PLAYER_MOVING42D                 392      /* BMP  */
#define PLAYER_MOVING42E                 393      /* BMP  */
#define PLAYER_MOVING42F                 394      /* BMP  */
#define PLAYER_MOVING52                  395      /* BMP  */
#define PLAYER_MOVING52A                 396      /* BMP  */
#define PLAYER_MOVING52B                 397      /* BMP  */
#define PLAYER_MOVING52C                 398      /* BMP  */
#define PLAYER_MOVING52D                 399      /* BMP  */
#define PLAYER_MOVING52E                 400      /* BMP  */
#define PLAYER_MOVING52F                 401      /* BMP  */
#define PLAYERD                          402      /* BMP  */
#define PORTA1                           403      /* BMP  */
#define PORTA2                           404      /* BMP  */
#define PORTAL1                          405      /* BMP  */
#define PORTAL2                          406      /* BMP  */
#define PORTAL3                          407      /* BMP  */
#define PORTAL4                          408      /* BMP  */
#define PORTAL5                          409      /* BMP  */
#define PORTAL6                          410      /* BMP  */
#define POSTE                            411      /* BMP  */
#define POWER                            412      /* BMP  */
#define PPP1                             413      /* BMP  */
#define PPP2                             414      /* BMP  */
#define PPP3                             415      /* BMP  */
#define PPP4                             416      /* BMP  */
#define PPP5                             417      /* BMP  */
#define PPP6                             418      /* BMP  */
#define PUMPKIN01                        419      /* BMP  */
#define PUMPKIN02                        420      /* BMP  */
#define PUMPKIN03                        421      /* BMP  */
#define PUMPKIN04                        422      /* BMP  */
#define PUMPKIN05                        423      /* BMP  */
#define QUICAR                           424      /* SAMP */
#define QUIT1                            425      /* BMP  */
#define QUIT2                            426      /* BMP  */
#define QUIT3                            427      /* BMP  */
#define QUIT4                            428      /* BMP  */
#define QUITGAME                         429      /* BMP  */
#define RAIN                             430      /* BMP  */
#define READY                            431      /* BMP  */
#define RECOVERY_L                       432      /* BMP  */
#define RECOVERY_M                       433      /* BMP  */
#define RECOVERY_S                       434      /* BMP  */
#define RECUPERATOR                      435      /* SAMP */
#define RECUPERATORS                     436      /* SAMP */
#define RED_TANK                         437      /* BMP  */
#define RED_TANK_2                       438      /* BMP  */
#define RED_TANK_3                       439      /* BMP  */
#define REDBALL01                        440      /* BMP  */
#define REDBALL02                        441      /* BMP  */
#define REDBALL03                        442      /* BMP  */
#define REDBALL04                        443      /* BMP  */
#define REDBALL05                        444      /* BMP  */
#define RESETTI                          445      /* BMP  */
#define RETURN                           446      /* BMP  */
#define ROAR                             447      /* SAMP */
#define ROAR2                            448      /* SAMP */
#define SAND                             449      /* BMP  */
#define SANDMORRO1                       450      /* BMP  */
#define SANDMORRO2                       451      /* BMP  */
#define SANDMORRO3                       452      /* BMP  */
#define SANDMORRO4                       453      /* BMP  */
#define SANDS                            454      /* SAMP */
#define SAVEGAME                         455      /* BMP  */
#define SC01                             456      /* BMP  */
#define SC02                             457      /* BMP  */
#define SC03                             458      /* BMP  */
#define SC04                             459      /* BMP  */
#define SC05                             460      /* BMP  */
#define SC06                             461      /* BMP  */
#define SC07                             462      /* BMP  */
#define SC08                             463      /* BMP  */
#define SC09                             464      /* BMP  */
#define SC10                             465      /* BMP  */
#define SC11                             466      /* BMP  */
#define SC12                             467      /* BMP  */
#define SCALED01                         468      /* BMP  */
#define SCALED02                         469      /* BMP  */
#define SCALED03                         470      /* BMP  */
#define SCALED04                         471      /* BMP  */
#define SCALEDCUT01                      472      /* BMP  */
#define SCALEDCUT02                      473      /* BMP  */
#define SCALEDFIRE01                     474      /* BMP  */
#define SCALEDFIRE02                     475      /* BMP  */
#define SCALEDFIRE03                     476      /* BMP  */
#define SEAHORSE1                        477      /* BMP  */
#define SEAHORSE2                        478      /* BMP  */
#define SEAHORSE3                        479      /* BMP  */
#define SELECT                           480      /* BMP  */
#define SELECT2                          481      /* BMP  */
#define SETA                             482      /* BMP  */
#define SETA2                            483      /* BMP  */
#define SFIRE1                           484      /* BMP  */
#define SFIRE2                           485      /* BMP  */
#define SFIRE3                           486      /* BMP  */
#define SFIRE4                           487      /* BMP  */
#define SFIRE5                           488      /* BMP  */
#define SFIRE6                           489      /* BMP  */
#define SFIRE7                           490      /* BMP  */
#define SHADOW                           491      /* BMP  */
#define SHADOW01                         492      /* BMP  */
#define SHADOW02                         493      /* BMP  */
#define SHADOW03                         494      /* BMP  */
#define SHADOWBALL                       495      /* BMP  */
#define SHADOWSHOT                       496      /* BMP  */
#define SHADOWSPIKE                      497      /* BMP  */
#define SHIELD                           498      /* BMP  */
#define SHOCKER01                        499      /* BMP  */
#define SHOCKER02                        500      /* BMP  */
#define SHOCKER03                        501      /* BMP  */
#define SHOCKER04                        502      /* BMP  */
#define SHOCKER05                        503      /* BMP  */
#define SHOCKING01                       504      /* BMP  */
#define SHOCKING02                       505      /* BMP  */
#define SHOCKING03                       506      /* BMP  */
#define SHOCKING04                       507      /* BMP  */
#define SHOCKING05                       508      /* BMP  */
#define SHOT                             509      /* BMP  */
#define SHOT_0_1                         510      /* BMP  */
#define SHOT_0_2                         511      /* BMP  */
#define SHOT_0_3                         512      /* BMP  */
#define SHOT_13_1                        513      /* BMP  */
#define SHOT_13_2                        514      /* BMP  */
#define SHOT_13_3                        515      /* BMP  */
#define SILENT                           516      /* BMP  */
#define SLASH01                          517      /* BMP  */
#define SLASH02                          518      /* BMP  */
#define SLEEP                            519      /* BMP  */
#define SNOW                             520      /* BMP  */
#define SONG                             521      /* BMP  */
#define SPARKLE                          522      /* SAMP */
#define SPARKLE1                         523      /* BMP  */
#define SPARKLE2                         524      /* BMP  */
#define SPARKLE3                         525      /* BMP  */
#define SPARKLE4                         526      /* BMP  */
#define SPLAASH                          527      /* SAMP */
#define SPLASH                           528      /* SAMP */
#define SPLASH1                          529      /* BMP  */
#define SPLASH2                          530      /* BMP  */
#define SPLASH3                          531      /* BMP  */
#define STAFFA                           532      /* BMP  */
#define STAFFB                           533      /* BMP  */
#define STAFFC                           534      /* BMP  */
#define STAFFD                           535      /* BMP  */
#define STAFFE                           536      /* BMP  */
#define STAFFF                           537      /* BMP  */
#define STAFFG                           538      /* BMP  */
#define STAFFH                           539      /* BMP  */
#define STAFFI                           540      /* BMP  */
#define STAFFJ                           541      /* BMP  */
#define STAFFK                           542      /* BMP  */
#define STAFFL                           543      /* BMP  */
#define STAFFM                           544      /* BMP  */
#define STAFFN                           545      /* BMP  */
#define STAFFO                           546      /* BMP  */
#define STAFFP                           547      /* BMP  */
#define STAFFQ                           548      /* BMP  */
#define STAFFR                           549      /* BMP  */
#define STAFFS                           550      /* BMP  */
#define STAFFT                           551      /* BMP  */
#define STAFFU                           552      /* BMP  */
#define STAFFV                           553      /* BMP  */
#define STAFFW                           554      /* BMP  */
#define STAFFX                           555      /* BMP  */
#define STAFFY                           556      /* BMP  */
#define STAFFZ                           557      /* BMP  */
#define STAGEFIRE                        558      /* BMP  */
#define STAGEFIRE2                       559      /* BMP  */
#define STAGEICE                         560      /* BMP  */
#define STAGEICE2                        561      /* BMP  */
#define STAGESHADOW                      562      /* BMP  */
#define STAGESHADOW2                     563      /* BMP  */
#define STAGETHUNDER                     564      /* BMP  */
#define STAGETHUNDER2                    565      /* BMP  */
#define STAGEWATER                       566      /* BMP  */
#define STAGEWATER2                      567      /* BMP  */
#define STAGEWIND                        568      /* BMP  */
#define STAGEWIND2                       569      /* BMP  */
#define START01                          570      /* BMP  */
#define START02                          571      /* BMP  */
#define START03                          572      /* BMP  */
#define START04                          573      /* BMP  */
#define START05                          574      /* BMP  */
#define START06                          575      /* BMP  */
#define STORM                            576      /* BMP  */
#define SWEET                            577      /* BMP  */
#define SWORD                            578      /* BMP  */
#define TEXTURES01                       579      /* BMP  */
#define TEXTURES02                       580      /* BMP  */
#define TEXTURES04                       581      /* BMP  */
#define TEXTURES05                       582      /* BMP  */
#define TEXTURES06                       583      /* BMP  */
#define TEXTURES07                       584      /* BMP  */
#define TEXTURES08                       585      /* BMP  */
#define TEXTURES09                       586      /* BMP  */
#define THANKS                           587      /* BMP  */
#define THE                              588      /* BMP  */
#define THEEND                           589      /* BMP  */
#define THROUGH                          590      /* BMP  */
#define THUNDER                          591      /* BMP  */
#define THUNDER01                        592      /* BMP  */
#define THUNDER02                        593      /* BMP  */
#define THUNDER03                        594      /* BMP  */
#define THUNDER04                        595      /* BMP  */
#define THUNDER05                        596      /* BMP  */
#define THUNDER_SHOT01                   597      /* BMP  */
#define THUNDER_SHOT02                   598      /* BMP  */
#define THUNDER_SHOT03                   599      /* BMP  */
#define THUNDERRAIO01                    600      /* BMP  */
#define THUNDERRAIO02                    601      /* BMP  */
#define THUNDERRAIO03                    602      /* BMP  */
#define THUNDERRAIO04                    603      /* BMP  */
#define THUNDERSOUND                     604      /* SAMP */
#define THUNDERUP01                      605      /* BMP  */
#define THUNDERUP02                      606      /* BMP  */
#define THUNDERUP03                      607      /* BMP  */
#define THUNDERUP04                      608      /* BMP  */
#define TIME                             609      /* BMP  */
#define TIRO1                            610      /* SAMP */
#define TIRO2                            611      /* SAMP */
#define TIRO3                            612      /* SAMP */
#define TIRO4                            613      /* SAMP */
#define TIRO5                            614      /* SAMP */
#define TIRO6                            615      /* SAMP */
#define TIRO7                            616      /* SAMP */
#define TOLETED_1                        617      /* BMP  */
#define TOLETED_2                        618      /* BMP  */
#define TOLETED_3                        619      /* BMP  */
#define TURRET                           620      /* SAMP */
#define TURRET_SHOT                      621      /* BMP  */
#define TURTLE                           622      /* BMP  */
#define TURTLE_ENTER1                    623      /* BMP  */
#define TURTLE_ENTER2                    624      /* BMP  */
#define TURTLE_ENTER3                    625      /* BMP  */
#define TURTLE_OPEN1                     626      /* BMP  */
#define TURTLE_OPEN2                     627      /* BMP  */
#define TURTLEDASH                       628      /* SAMP */
#define TURTLEJATO                       629      /* SAMP */
#define TWIN                             630      /* BMP  */
#define V0                               631      /* BMP  */
#define V1                               632      /* BMP  */
#define V2                               633      /* BMP  */
#define V3                               634      /* BMP  */
#define V4                               635      /* BMP  */
#define V5                               636      /* BMP  */
#define V6                               637      /* BMP  */
#define V7                               638      /* BMP  */
#define V8                               639      /* BMP  */
#define V9                               640      /* BMP  */
#define VIDA                             641      /* BMP  */
#define VIDA1                            642      /* BMP  */
#define VIDAA                            643      /* BMP  */
#define VIDAA1                           644      /* BMP  */
#define VIDAB                            645      /* BMP  */
#define VIDAB1                           646      /* BMP  */
#define VIDAC                            647      /* BMP  */
#define VIDAC1                           648      /* BMP  */
#define VIDAD                            649      /* BMP  */
#define VIDAD1                           650      /* BMP  */
#define VIDAE                            651      /* BMP  */
#define VIDAE1                           652      /* BMP  */
#define VIDAF                            653      /* BMP  */
#define VIDAF1                           654      /* BMP  */
#define VIDAZ                            655      /* BMP  */
#define VOICE                            656      /* BMP  */
#define WALLMAGIC                        657      /* BMP  */
#define WALLTURRET                       658      /* BMP  */
#define WALLTURRET2                      659      /* BMP  */
#define WATER_FIM1                       660      /* BMP  */
#define WATER_FIM2                       661      /* BMP  */
#define WATER_MEIO1                      662      /* BMP  */
#define WATER_MEIO2                      663      /* BMP  */
#define WATER_PONTA1                     664      /* BMP  */
#define WATER_PONTA2                     665      /* BMP  */
#define WATERSHOT                        666      /* BMP  */
#define WATERSHOTHIT1                    667      /* BMP  */
#define WATERSHOTHIT2                    668      /* BMP  */
#define WATERSHOTHIT3                    669      /* BMP  */
#define WATERSHOTHIT4                    670      /* BMP  */
#define WATERSHOTHIT5                    671      /* BMP  */
#define WATERSHOTHIT6                    672      /* BMP  */
#define WATERSHOTHIT7                    673      /* BMP  */
#define WATERSHOTHIT8                    674      /* BMP  */
#define WATERSHOTHIT9                    675      /* BMP  */
#define WATERSHOTSMALL                   676      /* BMP  */
#define WATERY                           677      /* BMP  */
#define WAVE                             678      /* BMP  */
#define WIND_SHOT01                      679      /* BMP  */
#define WIND_SHOT02                      680      /* BMP  */
#define WIND_SHOT03                      681      /* BMP  */
#define WINDMILL0                        682      /* BMP  */
#define WINDMILL1                        683      /* BMP  */
#define WINDOW                           684      /* BMP  */
#define WINDY                            685      /* BMP  */
#define WINDY01                          686      /* BMP  */
#define WINDY02                          687      /* BMP  */
#define WINDYDASH                        688      /* SAMP */
#define WOOD                             689      /* BMP  */
#define WTS                              690      /* SAMP */
#define WTSHOT01                         691      /* BMP  */
#define WTSHOT02                         692      /* BMP  */
#define WTSHOT03                         693      /* BMP  */
#define YELLOW_TOSKO_SHOT                694      /* BMP  */
#define ZOCK01                           695      /* BMP  */
#define ZOCK02                           696      /* BMP  */
#define ZOCK03                           697      /* BMP  */
#define ZOCK04                           698      /* BMP  */

