/* Allegro datafile object indexes, produced by grabber v4.1.17 (WIP), MinGW32 */
/* Datafile: c:\WINDOWS\Desktop\Lucas\Joguito\files.dat */
/* Date: Tue Aug 28 21:41:50 2007 */
/* Do not hand edit! */

#define ACCEPT                           0        /* SAMP */
#define AGUA                             1        /* BMP  */
#define AGUAT1                           2        /* BMP  */
#define AGUAT2                           3        /* BMP  */
#define AGUAT3                           4        /* BMP  */
#define ANIM13                           5        /* SAMP */
#define ANIM40                           6        /* SAMP */
#define ANIM60                           7        /* SAMP */
#define ARMOREYES1                       8        /* BMP  */
#define ARMOREYES2                       9        /* BMP  */
#define ARMOREYES3                       10       /* BMP  */
#define ARMOREYES4                       11       /* BMP  */
#define ARROW                            12       /* BMP  */
#define BACULO                           13       /* BMP  */
#define BIG                              14       /* BMP  */
#define BIGTHUNDER                       15       /* SAMP */
#define BIRD1                            16       /* BMP  */
#define BIRD2                            17       /* BMP  */
#define BIRD3                            18       /* BMP  */
#define BIRDFLY1                         19       /* BMP  */
#define BIRDFLY2                         20       /* BMP  */
#define BIRDSTAND                        21       /* BMP  */
#define BIRDSTAND1                       22       /* BMP  */
#define BIRDSTAND2                       23       /* BMP  */
#define BIRDSTAND3                       24       /* BMP  */
#define BLOCK                            25       /* BMP  */
#define BOLHAS                           26       /* BMP  */
#define BUBBLES                          27       /* BMP  */
#define CARD01                           28       /* BMP  */
#define CARD02                           29       /* BMP  */
#define CARD03                           30       /* BMP  */
#define CARD04                           31       /* BMP  */
#define CARD05                           32       /* BMP  */
#define CARDBACK1                        33       /* BMP  */
#define CARDBACK2                        34       /* BMP  */
#define CARDBACK3                        35       /* BMP  */
#define CARDGET                          36       /* SAMP */
#define CARDHOLDER                       37       /* BMP  */
#define CARDHOLDER2                      38       /* BMP  */
#define CHANGE                           39       /* BMP  */
#define CLOUD                            40       /* BMP  */
#define CREATE                           41       /* BMP  */
#define CREDITS1                         42       /* BMP  */
#define CREDITS2                         43       /* BMP  */
#define CREDITS3                         44       /* BMP  */
#define CREDITS4                         45       /* BMP  */
#define CREDITS5                         46       /* BMP  */
#define CREDITS6                         47       /* BMP  */
#define CSELECT                          48       /* BMP  */
#define DA400                            49       /* BMP  */
#define DA401                            50       /* BMP  */
#define DA402                            51       /* BMP  */
#define DA600                            52       /* BMP  */
#define DA601                            53       /* BMP  */
#define DA602                            54       /* BMP  */
#define DARK                             55       /* BMP  */
#define DASH                             56       /* BMP  */
#define DENY                             57       /* SAMP */
#define DESTROYABLEPAREDE                58       /* BMP  */
#define DESTROYABLEPAREDE2               59       /* BMP  */
#define DIE                              60       /* SAMP */
#define DREAM                            61       /* BMP  */
#define EARTHY                           62       /* BMP  */
#define ENDING1                          63       /* BMP  */
#define ENDING2                          64       /* BMP  */
#define ENDING3                          65       /* BMP  */
#define ENDING4                          66       /* BMP  */
#define ENDING5                          67       /* BMP  */
#define ENDING6                          68       /* BMP  */
#define ENDINGFONT                       69       /* FONT */
#define ERASE                            70       /* BMP  */
#define EWUL_SQUID01                     71       /* BMP  */
#define EWUL_SQUID02                     72       /* BMP  */
#define EWUL_SQUID03                     73       /* BMP  */
#define EWUL_SQUID04                     74       /* BMP  */
#define EWUL_SQUID05                     75       /* BMP  */
#define EWUL_SQUID06                     76       /* BMP  */
#define EWULARMOR1                       77       /* BMP  */
#define EWULARMOR2                       78       /* BMP  */
#define EWULFISH_11                      79       /* BMP  */
#define EWULFISH_12                      80       /* BMP  */
#define EWULFISH_13                      81       /* BMP  */
#define EWULFISH_21                      82       /* BMP  */
#define EWULFISH_22                      83       /* BMP  */
#define EWULFISH_23                      84       /* BMP  */
#define EWULFISH_31                      85       /* BMP  */
#define EWULFISH_32                      86       /* BMP  */
#define EWULFISH_33                      87       /* BMP  */
#define EWULFISH_41                      88       /* BMP  */
#define EWULFISH_42                      89       /* BMP  */
#define EWULFISH_43                      90       /* BMP  */
#define EWULMACHINE01                    91       /* BMP  */
#define EWULMISSILE                      92       /* SAMP */
#define EWULMISSILE01                    93       /* BMP  */
#define EWULOSTRABALLB                   94       /* BMP  */
#define EWULOSTRABALLW                   95       /* BMP  */
#define EWULOSTRAPT1                     96       /* BMP  */
#define EWULOSTRAPT2                     97       /* BMP  */
#define EWULOSTRAPT3                     98       /* BMP  */
#define EWULOSTRAPT4                     99       /* BMP  */
#define EXIT                             100      /* BMP  */
#define FIGHT                            101      /* BMP  */
#define FIRE1                            102      /* BMP  */
#define FIRE2                            103      /* BMP  */
#define FIRE3                            104      /* BMP  */
#define FIRE4                            105      /* BMP  */
#define FIRE5                            106      /* BMP  */
#define FIRE6                            107      /* BMP  */
#define FIRE7                            108      /* BMP  */
#define FIRESLASH                        109      /* SAMP */
#define FIREY                            110      /* BMP  */
#define FIREYFLAME                       111      /* SAMP */
#define FLAMEMET1                        112      /* BMP  */
#define FLAMEMET2                        113      /* BMP  */
#define FLAMEMET3                        114      /* BMP  */
#define FLAMEMET4                        115      /* BMP  */
#define FLAMES01                         116      /* BMP  */
#define FLAMES02                         117      /* BMP  */
#define FLAMES03                         118      /* BMP  */
#define FLAMES04                         119      /* BMP  */
#define FLAMES05                         120      /* BMP  */
#define FLAMES06                         121      /* BMP  */
#define FLAMES07                         122      /* BMP  */
#define FLAMES08                         123      /* BMP  */
#define FLAMES09                         124      /* BMP  */
#define FLAMES11                         125      /* BMP  */
#define FLAMES12                         126      /* BMP  */
#define FLAMES13                         127      /* BMP  */
#define FLAMES14                         128      /* BMP  */
#define FLAMES15                         129      /* BMP  */
#define FLAMES16                         130      /* BMP  */
#define FLAMES17                         131      /* BMP  */
#define FLAMES18                         132      /* BMP  */
#define FLAMES19                         133      /* BMP  */
#define FLAMETHROWER                     134      /* SAMP */
#define FLAMETHROWER1                    135      /* BMP  */
#define FLAMETHROWER2                    136      /* BMP  */
#define FLOAT                            137      /* BMP  */
#define FLOWER                           138      /* BMP  */
#define FLY                              139      /* BMP  */
#define FREEZE                           140      /* BMP  */
#define GHOST01                          141      /* BMP  */
#define GHOST02                          142      /* BMP  */
#define GHOST03                          143      /* BMP  */
#define GHOST04                          144      /* BMP  */
#define GHOSTMASK01                      145      /* BMP  */
#define GHOSTMASK02                      146      /* BMP  */
#define GHOSTMASK03                      147      /* BMP  */
#define GLASS                            148      /* SAMP */
#define GLOW                             149      /* BMP  */
#define GREEN_TURRET                     150      /* BMP  */
#define GUILHOTINA                       151      /* BMP  */
#define HA                               152      /* BMP  */
#define HADOUKEN01                       153      /* BMP  */
#define HADOUKEN02                       154      /* BMP  */
#define HADOUKEN03                       155      /* BMP  */
#define HADOUKEN04                       156      /* BMP  */
#define HADOUKEN05                       157      /* BMP  */
#define HADOUKEN06                       158      /* BMP  */
#define HADOUKEN07                       159      /* BMP  */
#define HADUEX                           160      /* SAMP */
#define ICE01                            161      /* BMP  */
#define ICE02                            162      /* BMP  */
#define ICEANIM                          163      /* SAMP */
#define ICEBLOCK1                        164      /* BMP  */
#define ICEBLOCK2                        165      /* BMP  */
#define ICEDESTROY                       166      /* BMP  */
#define ICEFALL                          167      /* SAMP */
#define ICEHOLDER1                       168      /* BMP  */
#define ICEHOLDER2                       169      /* BMP  */
#define ICEHOLDER3                       170      /* BMP  */
#define ICEHOLDER4                       171      /* BMP  */
#define ICEMET01                         172      /* BMP  */
#define ICEMET02                         173      /* BMP  */
#define ICEMET03                         174      /* BMP  */
#define ICEMET04                         175      /* BMP  */
#define ICENEEDLE01                      176      /* BMP  */
#define ICENEEDLE02                      177      /* BMP  */
#define ICENEEDLE03                      178      /* BMP  */
#define ICENEEDLE04                      179      /* BMP  */
#define ICESPIKE                         180      /* BMP  */
#define ICETOP                           181      /* BMP  */
#define ICETOP2                          182      /* BMP  */
#define ICYATTACK01                      183      /* BMP  */
#define ICYATTACK02                      184      /* BMP  */
#define ICYATTACK03                      185      /* BMP  */
#define ICYATTACK04                      186      /* BMP  */
#define ICYATTACK05                      187      /* BMP  */
#define ICYATTACK06                      188      /* BMP  */
#define ICYSHADOW01                      189      /* BMP  */
#define ICYSHADOW02                      190      /* BMP  */
#define ICYSHADOW03                      191      /* BMP  */
#define ICYSHADOW04                      192      /* BMP  */
#define ICYSIDE01                        193      /* BMP  */
#define ICYSIDE02                        194      /* BMP  */
#define ICYSIDE03                        195      /* BMP  */
#define ICYSIDE04                        196      /* BMP  */
#define ICYUP01                          197      /* BMP  */
#define ICYUP02                          198      /* BMP  */
#define ICYUP03                          199      /* BMP  */
#define ILLUSION                         200      /* BMP  */
#define IRON_DOOR                        201      /* BMP  */
#define JUMP                             202      /* BMP  */
#define LASTBALL1                        203      /* BMP  */
#define LASTBALL2                        204      /* BMP  */
#define LASTBALL3                        205      /* BMP  */
#define LASTBALL4                        206      /* BMP  */
#define LASTBOSS                         207      /* BMP  */
#define LASTS                            208      /* SAMP */
#define LASTSMALL1                       209      /* BMP  */
#define LASTSMALL2                       210      /* BMP  */
#define LASTSMALL3                       211      /* BMP  */
#define LASTSMALL4                       212      /* BMP  */
#define LAVA1                            213      /* BMP  */
#define LAVA2                            214      /* BMP  */
#define LAVA3                            215      /* BMP  */
#define LIBRA                            216      /* BMP  */
#define LIFEBAR                          217      /* BMP  */
#define LIFEMETER                        218      /* BMP  */
#define LIFEMETER2                       219      /* BMP  */
#define LIFEMETERBOSS                    220      /* BMP  */
#define LIGHT                            221      /* BMP  */
#define LITTLE                           222      /* BMP  */
#define LOAD1                            223      /* BMP  */
#define LOAD2                            224      /* BMP  */
#define LOAD3                            225      /* BMP  */
#define LOAD4                            226      /* BMP  */
#define LOCK                             227      /* BMP  */
#define LOOP                             228      /* BMP  */
#define LUZ                              229      /* BMP  */
#define MAINMENU                         230      /* BMP  */
#define MAZE                             231      /* BMP  */
#define MENU                             232      /* BMP  */
#define MENU_EX2                         233      /* BMP  */
#define MENU_FI                          234      /* BMP  */
#define MENU_FI2                         235      /* BMP  */
#define MENU_FR                          236      /* BMP  */
#define MENU_FR2                         237      /* BMP  */
#define MENU_MA2                         238      /* BMP  */
#define MENU_SH                          239      /* BMP  */
#define MENU_SH2                         240      /* BMP  */
#define MENU_TH                          241      /* BMP  */
#define MENU_TH2                         242      /* BMP  */
#define MENU_WA                          243      /* BMP  */
#define MENU_WA2                         244      /* BMP  */
#define MENU_WI                          245      /* BMP  */
#define MENU_WI2                         246      /* BMP  */
#define MENUBACK                         247      /* BMP  */
#define MENUOPTIONS                      248      /* BMP  */
#define MENUWINDOW                       249      /* BMP  */
#define MENUWINDOW2                      250      /* BMP  */
#define MENUWINDY                        251      /* BMP  */
#define MIRROR                           252      /* BMP  */
#define MIST                             253      /* BMP  */
#define MOLA_FELIZ                       254      /* BMP  */
#define MOLA_FELIZ2                      255      /* BMP  */
#define MOVE                             256      /* BMP  */
#define NEWGAME1                         257      /* BMP  */
#define NEWGAME2                         258      /* BMP  */
#define NEWGAME3                         259      /* BMP  */
#define NEWGAME4                         260      /* BMP  */
#define NULO                             261      /* BMP  */
#define OPTIONS                          262      /* BMP  */
#define OPTIONS1                         263      /* BMP  */
#define OPTIONS2                         264      /* BMP  */
#define OPTIONS3                         265      /* BMP  */
#define OPTIONS4                         266      /* BMP  */
#define ORANGE01                         267      /* BMP  */
#define ORANGE02                         268      /* BMP  */
#define ORANGE03                         269      /* BMP  */
#define ORANGE04                         270      /* BMP  */
#define ORANGE05                         271      /* BMP  */
#define ORANGE06                         272      /* BMP  */
#define ORANGE07                         273      /* BMP  */
#define ORANGE08                         274      /* BMP  */
#define ORANGE09                         275      /* BMP  */
#define ORANGEH01                        276      /* BMP  */
#define ORANGEH02                        277      /* BMP  */
#define ORANGEH03                        278      /* BMP  */
#define PAINTING1                        279      /* BMP  */
#define PAINTING2                        280      /* BMP  */
#define PARTICLEDESTROY1                 281      /* BMP  */
#define PARTICLEDESTROY2                 282      /* BMP  */
#define PARTICLES01                      283      /* BMP  */
#define PARTICLES02                      284      /* BMP  */
#define PARTICLES03                      285      /* BMP  */
#define PARTICLES04                      286      /* BMP  */
#define PDIE1                            287      /* BMP  */
#define PDIE2                            288      /* BMP  */
#define PDIE3                            289      /* BMP  */
#define PDIE4                            290      /* BMP  */
#define PDIE5                            291      /* BMP  */
#define PENA                             292      /* BMP  */
#define PENASOUND                        293      /* SAMP */
#define PIRIKITO                         294      /* BMP  */
#define PIRIKITO2                        295      /* BMP  */
#define PIRIKITO3                        296      /* BMP  */
#define PISK1                            297      /* BMP  */
#define PISK2                            298      /* BMP  */
#define PLAYER_MOVING01                  299      /* BMP  */
#define PLAYER_MOVING01A                 300      /* BMP  */
#define PLAYER_MOVING01B                 301      /* BMP  */
#define PLAYER_MOVING01C                 302      /* BMP  */
#define PLAYER_MOVING01D                 303      /* BMP  */
#define PLAYER_MOVING01E                 304      /* BMP  */
#define PLAYER_MOVING01F                 305      /* BMP  */
#define PLAYER_MOVING02                  306      /* BMP  */
#define PLAYER_MOVING02A                 307      /* BMP  */
#define PLAYER_MOVING02B                 308      /* BMP  */
#define PLAYER_MOVING02C                 309      /* BMP  */
#define PLAYER_MOVING02D                 310      /* BMP  */
#define PLAYER_MOVING02E                 311      /* BMP  */
#define PLAYER_MOVING02F                 312      /* BMP  */
#define PLAYER_MOVING03                  313      /* BMP  */
#define PLAYER_MOVING03A                 314      /* BMP  */
#define PLAYER_MOVING03B                 315      /* BMP  */
#define PLAYER_MOVING03C                 316      /* BMP  */
#define PLAYER_MOVING03D                 317      /* BMP  */
#define PLAYER_MOVING03E                 318      /* BMP  */
#define PLAYER_MOVING03F                 319      /* BMP  */
#define PLAYER_MOVING04                  320      /* BMP  */
#define PLAYER_MOVING04A                 321      /* BMP  */
#define PLAYER_MOVING04B                 322      /* BMP  */
#define PLAYER_MOVING04C                 323      /* BMP  */
#define PLAYER_MOVING04D                 324      /* BMP  */
#define PLAYER_MOVING04E                 325      /* BMP  */
#define PLAYER_MOVING04F                 326      /* BMP  */
#define PLAYER_MOVING05                  327      /* BMP  */
#define PLAYER_MOVING05A                 328      /* BMP  */
#define PLAYER_MOVING05B                 329      /* BMP  */
#define PLAYER_MOVING05C                 330      /* BMP  */
#define PLAYER_MOVING05D                 331      /* BMP  */
#define PLAYER_MOVING05E                 332      /* BMP  */
#define PLAYER_MOVING05F                 333      /* BMP  */
#define PLAYER_MOVING12                  334      /* BMP  */
#define PLAYER_MOVING12A                 335      /* BMP  */
#define PLAYER_MOVING12B                 336      /* BMP  */
#define PLAYER_MOVING12C                 337      /* BMP  */
#define PLAYER_MOVING12D                 338      /* BMP  */
#define PLAYER_MOVING12E                 339      /* BMP  */
#define PLAYER_MOVING12F                 340      /* BMP  */
#define PLAYER_MOVING22                  341      /* BMP  */
#define PLAYER_MOVING22A                 342      /* BMP  */
#define PLAYER_MOVING22B                 343      /* BMP  */
#define PLAYER_MOVING22C                 344      /* BMP  */
#define PLAYER_MOVING22D                 345      /* BMP  */
#define PLAYER_MOVING22E                 346      /* BMP  */
#define PLAYER_MOVING22F                 347      /* BMP  */
#define PLAYER_MOVING32                  348      /* BMP  */
#define PLAYER_MOVING32A                 349      /* BMP  */
#define PLAYER_MOVING32B                 350      /* BMP  */
#define PLAYER_MOVING32C                 351      /* BMP  */
#define PLAYER_MOVING32D                 352      /* BMP  */
#define PLAYER_MOVING32E                 353      /* BMP  */
#define PLAYER_MOVING32F                 354      /* BMP  */
#define PLAYER_MOVING42                  355      /* BMP  */
#define PLAYER_MOVING42A                 356      /* BMP  */
#define PLAYER_MOVING42B                 357      /* BMP  */
#define PLAYER_MOVING42C                 358      /* BMP  */
#define PLAYER_MOVING42D                 359      /* BMP  */
#define PLAYER_MOVING42E                 360      /* BMP  */
#define PLAYER_MOVING42F                 361      /* BMP  */
#define PLAYER_MOVING52                  362      /* BMP  */
#define PLAYER_MOVING52A                 363      /* BMP  */
#define PLAYER_MOVING52B                 364      /* BMP  */
#define PLAYER_MOVING52C                 365      /* BMP  */
#define PLAYER_MOVING52D                 366      /* BMP  */
#define PLAYER_MOVING52E                 367      /* BMP  */
#define PLAYER_MOVING52F                 368      /* BMP  */
#define PLAYERD                          369      /* BMP  */
#define PORTA1                           370      /* BMP  */
#define PORTA2                           371      /* BMP  */
#define PORTAL1                          372      /* BMP  */
#define PORTAL2                          373      /* BMP  */
#define PORTAL3                          374      /* BMP  */
#define PORTAL4                          375      /* BMP  */
#define PORTAL5                          376      /* BMP  */
#define PORTAL6                          377      /* BMP  */
#define POSTE                            378      /* BMP  */
#define POWER                            379      /* BMP  */
#define PPP1                             380      /* BMP  */
#define PPP2                             381      /* BMP  */
#define PPP3                             382      /* BMP  */
#define PPP4                             383      /* BMP  */
#define PPP5                             384      /* BMP  */
#define PPP6                             385      /* BMP  */
#define PUMPKIN01                        386      /* BMP  */
#define PUMPKIN02                        387      /* BMP  */
#define PUMPKIN03                        388      /* BMP  */
#define PUMPKIN04                        389      /* BMP  */
#define PUMPKIN05                        390      /* BMP  */
#define QUICAR                           391      /* SAMP */
#define QUIT1                            392      /* BMP  */
#define QUIT2                            393      /* BMP  */
#define QUIT3                            394      /* BMP  */
#define QUIT4                            395      /* BMP  */
#define QUITGAME                         396      /* BMP  */
#define RAIN                             397      /* BMP  */
#define READY                            398      /* BMP  */
#define RECOVERY_L                       399      /* BMP  */
#define RECOVERY_M                       400      /* BMP  */
#define RECOVERY_S                       401      /* BMP  */
#define RECUPERATOR                      402      /* SAMP */
#define RECUPERATORS                     403      /* SAMP */
#define RED_TANK                         404      /* BMP  */
#define RED_TANK_2                       405      /* BMP  */
#define RED_TANK_3                       406      /* BMP  */
#define REDBALL01                        407      /* BMP  */
#define REDBALL02                        408      /* BMP  */
#define REDBALL03                        409      /* BMP  */
#define REDBALL04                        410      /* BMP  */
#define REDBALL05                        411      /* BMP  */
#define RESETTI                          412      /* BMP  */
#define RETURN                           413      /* BMP  */
#define ROAR                             414      /* SAMP */
#define ROAR2                            415      /* SAMP */
#define SAND                             416      /* BMP  */
#define SANDMORRO1                       417      /* BMP  */
#define SANDMORRO2                       418      /* BMP  */
#define SANDMORRO3                       419      /* BMP  */
#define SANDMORRO4                       420      /* BMP  */
#define SANDS                            421      /* SAMP */
#define SAVEGAME                         422      /* BMP  */
#define SC01                             423      /* BMP  */
#define SC02                             424      /* BMP  */
#define SC03                             425      /* BMP  */
#define SC04                             426      /* BMP  */
#define SC05                             427      /* BMP  */
#define SC06                             428      /* BMP  */
#define SC07                             429      /* BMP  */
#define SC08                             430      /* BMP  */
#define SC09                             431      /* BMP  */
#define SC10                             432      /* BMP  */
#define SC11                             433      /* BMP  */
#define SC12                             434      /* BMP  */
#define SCALED01                         435      /* BMP  */
#define SCALED02                         436      /* BMP  */
#define SCALED03                         437      /* BMP  */
#define SCALED04                         438      /* BMP  */
#define SCALEDCUT01                      439      /* BMP  */
#define SCALEDCUT02                      440      /* BMP  */
#define SCALEDFIRE01                     441      /* BMP  */
#define SCALEDFIRE02                     442      /* BMP  */
#define SCALEDFIRE03                     443      /* BMP  */
#define SEAHORSE1                        444      /* BMP  */
#define SEAHORSE2                        445      /* BMP  */
#define SEAHORSE3                        446      /* BMP  */
#define SELECT                           447      /* BMP  */
#define SELECT2                          448      /* BMP  */
#define SETA                             449      /* BMP  */
#define SETA2                            450      /* BMP  */
#define SFIRE1                           451      /* BMP  */
#define SFIRE2                           452      /* BMP  */
#define SFIRE3                           453      /* BMP  */
#define SFIRE4                           454      /* BMP  */
#define SFIRE5                           455      /* BMP  */
#define SFIRE6                           456      /* BMP  */
#define SFIRE7                           457      /* BMP  */
#define SHADOW                           458      /* BMP  */
#define SHADOW01                         459      /* BMP  */
#define SHADOW02                         460      /* BMP  */
#define SHADOW03                         461      /* BMP  */
#define SHADOWBALL                       462      /* BMP  */
#define SHADOWSHOT                       463      /* BMP  */
#define SHADOWSPIKE                      464      /* BMP  */
#define SHIELD                           465      /* BMP  */
#define SHOCKER01                        466      /* BMP  */
#define SHOCKER02                        467      /* BMP  */
#define SHOCKER03                        468      /* BMP  */
#define SHOCKER04                        469      /* BMP  */
#define SHOCKER05                        470      /* BMP  */
#define SHOCKING01                       471      /* BMP  */
#define SHOCKING02                       472      /* BMP  */
#define SHOCKING03                       473      /* BMP  */
#define SHOCKING04                       474      /* BMP  */
#define SHOCKING05                       475      /* BMP  */
#define SHOT                             476      /* BMP  */
#define SHOT_0_1                         477      /* BMP  */
#define SHOT_0_2                         478      /* BMP  */
#define SHOT_0_3                         479      /* BMP  */
#define SHOT_13_1                        480      /* BMP  */
#define SHOT_13_2                        481      /* BMP  */
#define SHOT_13_3                        482      /* BMP  */
#define SILENT                           483      /* BMP  */
#define SLASH01                          484      /* BMP  */
#define SLASH02                          485      /* BMP  */
#define SLEEP                            486      /* BMP  */
#define SNOW                             487      /* BMP  */
#define SONG                             488      /* BMP  */
#define SPARKLE                          489      /* SAMP */
#define SPARKLE1                         490      /* BMP  */
#define SPARKLE2                         491      /* BMP  */
#define SPARKLE3                         492      /* BMP  */
#define SPARKLE4                         493      /* BMP  */
#define SPLAASH                          494      /* SAMP */
#define SPLASH                           495      /* SAMP */
#define SPLASH1                          496      /* BMP  */
#define SPLASH2                          497      /* BMP  */
#define SPLASH3                          498      /* BMP  */
#define STAGEFIRE                        499      /* BMP  */
#define STAGEFIRE2                       500      /* BMP  */
#define STAGEICE                         501      /* BMP  */
#define STAGEICE2                        502      /* BMP  */
#define STAGESHADOW                      503      /* BMP  */
#define STAGESHADOW2                     504      /* BMP  */
#define STAGETHUNDER                     505      /* BMP  */
#define STAGETHUNDER2                    506      /* BMP  */
#define STAGEWATER                       507      /* BMP  */
#define STAGEWATER2                      508      /* BMP  */
#define STAGEWIND                        509      /* BMP  */
#define STAGEWIND2                       510      /* BMP  */
#define STORM                            511      /* BMP  */
#define SWEET                            512      /* BMP  */
#define SWORD                            513      /* BMP  */
#define TEXTURES01                       514      /* BMP  */
#define TEXTURES02                       515      /* BMP  */
#define TEXTURES04                       516      /* BMP  */
#define TEXTURES05                       517      /* BMP  */
#define TEXTURES06                       518      /* BMP  */
#define TEXTURES07                       519      /* BMP  */
#define TEXTURES08                       520      /* BMP  */
#define TEXTURES09                       521      /* BMP  */
#define THANKS                           522      /* BMP  */
#define THE                              523      /* BMP  */
#define THEEND                           524      /* BMP  */
#define THROUGH                          525      /* BMP  */
#define THUNDER                          526      /* BMP  */
#define THUNDER01                        527      /* BMP  */
#define THUNDER02                        528      /* BMP  */
#define THUNDER03                        529      /* BMP  */
#define THUNDER04                        530      /* BMP  */
#define THUNDER05                        531      /* BMP  */
#define THUNDER_SHOT01                   532      /* BMP  */
#define THUNDER_SHOT02                   533      /* BMP  */
#define THUNDER_SHOT03                   534      /* BMP  */
#define THUNDERRAIO01                    535      /* BMP  */
#define THUNDERRAIO02                    536      /* BMP  */
#define THUNDERRAIO03                    537      /* BMP  */
#define THUNDERRAIO04                    538      /* BMP  */
#define THUNDERSOUND                     539      /* SAMP */
#define THUNDERUP01                      540      /* BMP  */
#define THUNDERUP02                      541      /* BMP  */
#define THUNDERUP03                      542      /* BMP  */
#define THUNDERUP04                      543      /* BMP  */
#define TIME                             544      /* BMP  */
#define TIRO1                            545      /* SAMP */
#define TIRO2                            546      /* SAMP */
#define TIRO3                            547      /* SAMP */
#define TIRO4                            548      /* SAMP */
#define TIRO5                            549      /* SAMP */
#define TIRO6                            550      /* SAMP */
#define TIRO7                            551      /* SAMP */
#define TOLETED_1                        552      /* BMP  */
#define TOLETED_2                        553      /* BMP  */
#define TOLETED_3                        554      /* BMP  */
#define TURRET                           555      /* SAMP */
#define TURRET_SHOT                      556      /* BMP  */
#define TURTLE                           557      /* BMP  */
#define TURTLE_ENTER1                    558      /* BMP  */
#define TURTLE_ENTER2                    559      /* BMP  */
#define TURTLE_ENTER3                    560      /* BMP  */
#define TURTLE_OPEN1                     561      /* BMP  */
#define TURTLE_OPEN2                     562      /* BMP  */
#define TURTLEDASH                       563      /* SAMP */
#define TURTLEJATO                       564      /* SAMP */
#define TWIN                             565      /* BMP  */
#define V0                               566      /* BMP  */
#define V1                               567      /* BMP  */
#define V2                               568      /* BMP  */
#define V3                               569      /* BMP  */
#define V4                               570      /* BMP  */
#define V5                               571      /* BMP  */
#define V6                               572      /* BMP  */
#define V7                               573      /* BMP  */
#define V8                               574      /* BMP  */
#define V9                               575      /* BMP  */
#define VIDA                             576      /* BMP  */
#define VIDA1                            577      /* BMP  */
#define VIDAA                            578      /* BMP  */
#define VIDAA1                           579      /* BMP  */
#define VIDAB                            580      /* BMP  */
#define VIDAB1                           581      /* BMP  */
#define VIDAC                            582      /* BMP  */
#define VIDAC1                           583      /* BMP  */
#define VIDAD                            584      /* BMP  */
#define VIDAD1                           585      /* BMP  */
#define VIDAE                            586      /* BMP  */
#define VIDAE1                           587      /* BMP  */
#define VIDAF                            588      /* BMP  */
#define VIDAF1                           589      /* BMP  */
#define VIDAZ                            590      /* BMP  */
#define VOICE                            591      /* BMP  */
#define WALLMAGIC                        592      /* BMP  */
#define WALLTURRET                       593      /* BMP  */
#define WALLTURRET2                      594      /* BMP  */
#define WATER_FIM1                       595      /* BMP  */
#define WATER_FIM2                       596      /* BMP  */
#define WATER_MEIO1                      597      /* BMP  */
#define WATER_MEIO2                      598      /* BMP  */
#define WATER_PONTA1                     599      /* BMP  */
#define WATER_PONTA2                     600      /* BMP  */
#define WATERSHOT                        601      /* BMP  */
#define WATERSHOTHIT1                    602      /* BMP  */
#define WATERSHOTHIT2                    603      /* BMP  */
#define WATERSHOTHIT3                    604      /* BMP  */
#define WATERSHOTHIT4                    605      /* BMP  */
#define WATERSHOTHIT5                    606      /* BMP  */
#define WATERSHOTHIT6                    607      /* BMP  */
#define WATERSHOTHIT7                    608      /* BMP  */
#define WATERSHOTHIT8                    609      /* BMP  */
#define WATERSHOTHIT9                    610      /* BMP  */
#define WATERSHOTSMALL                   611      /* BMP  */
#define WATERY                           612      /* BMP  */
#define WAVE                             613      /* BMP  */
#define WIND_SHOT01                      614      /* BMP  */
#define WIND_SHOT02                      615      /* BMP  */
#define WIND_SHOT03                      616      /* BMP  */
#define WINDMILL0                        617      /* BMP  */
#define WINDMILL1                        618      /* BMP  */
#define WINDOW                           619      /* BMP  */
#define WINDY                            620      /* BMP  */
#define WINDY01                          621      /* BMP  */
#define WINDY02                          622      /* BMP  */
#define WINDYDASH                        623      /* SAMP */
#define WOOD                             624      /* BMP  */
#define WTS                              625      /* SAMP */
#define WTSHOT01                         626      /* BMP  */
#define WTSHOT02                         627      /* BMP  */
#define WTSHOT03                         628      /* BMP  */
#define YELLOW_TOSKO_SHOT                629      /* BMP  */
#define ZOCK01                           630      /* BMP  */
#define ZOCK02                           631      /* BMP  */
#define ZOCK03                           632      /* BMP  */
#define ZOCK04                           633      /* BMP  */

