/* Allegro datafile object indexes, produced by grabber v4.2.0, MSVC.s */
/* Datafile: c:\Users\Lucas\Desktop\grabber\files.dat */
/* Date: Sat Mar 10 12:25:06 2012 */
/* Do not hand edit! */

#define AAA                              0        /* BMP  */
#define ACCEPT                           1        /* SAMP */
#define AGUA                             2        /* BMP  */
#define AGUAT1                           3        /* BMP  */
#define AGUAT2                           4        /* BMP  */
#define AGUAT3                           5        /* BMP  */
#define ANIM13                           6        /* SAMP */
#define ANIM40                           7        /* SAMP */
#define ANIM60                           8        /* SAMP */
#define ARMOREYES1                       9        /* BMP  */
#define ARMOREYES2                       10       /* BMP  */
#define ARMOREYES3                       11       /* BMP  */
#define ARMOREYES4                       12       /* BMP  */
#define ARROW                            13       /* BMP  */
#define ASINHAKAWAII                     14       /* BMP  */
#define BACULO                           15       /* BMP  */
#define BG1                              16       /* BMP  */
#define BG2                              17       /* BMP  */
#define BG3                              18       /* BMP  */
#define BG4                              19       /* BMP  */
#define BG5                              20       /* BMP  */
#define BG6                              21       /* BMP  */
#define BG7                              22       /* BMP  */
#define BG8                              23       /* BMP  */
#define BGM1                             24       /* MIDI */
#define BGM2                             25       /* MIDI */
#define BGM3                             26       /* MIDI */
#define BGM4                             27       /* MIDI */
#define BGM5                             28       /* MIDI */
#define BGM6                             29       /* MIDI */
#define BGM7                             30       /* MIDI */
#define BGM8                             31       /* MIDI */
#define BGM9                             32       /* MIDI */
#define BGMA                             33       /* MIDI */
#define BGMB                             34       /* MIDI */
#define BIG                              35       /* BMP  */
#define BIGTHUNDER                       36       /* SAMP */
#define BIRD1                            37       /* BMP  */
#define BIRD2                            38       /* BMP  */
#define BIRD3                            39       /* BMP  */
#define BIRDFLY1                         40       /* BMP  */
#define BIRDFLY2                         41       /* BMP  */
#define BIRDSTAND                        42       /* BMP  */
#define BIRDSTAND1                       43       /* BMP  */
#define BIRDSTAND2                       44       /* BMP  */
#define BIRDSTAND3                       45       /* BMP  */
#define BLOCK                            46       /* BMP  */
#define BOLHAS                           47       /* BMP  */
#define BOULDERLOL                       48       /* BMP  */
#define BUBBLES                          49       /* BMP  */
#define CARD01                           50       /* BMP  */
#define CARD02                           51       /* BMP  */
#define CARD03                           52       /* BMP  */
#define CARD04                           53       /* BMP  */
#define CARD05                           54       /* BMP  */
#define CARDBACK1                        55       /* BMP  */
#define CARDBACK2                        56       /* BMP  */
#define CARDBACK3                        57       /* BMP  */
#define CARDGET                          58       /* SAMP */
#define CARDHOLDER                       59       /* BMP  */
#define CARDHOLDER2                      60       /* BMP  */
#define CHANGE                           61       /* BMP  */
#define CHEAT                            62       /* BMP  */
#define CLOUD                            63       /* BMP  */
#define CREATE                           64       /* BMP  */
#define CREDITS1                         65       /* BMP  */
#define CREDITS2                         66       /* BMP  */
#define CREDITS3                         67       /* BMP  */
#define CREDITS4                         68       /* BMP  */
#define CREDITS5                         69       /* BMP  */
#define CREDITS6                         70       /* BMP  */
#define CSELECT                          71       /* BMP  */
#define DA400                            72       /* BMP  */
#define DA401                            73       /* BMP  */
#define DA402                            74       /* BMP  */
#define DA600                            75       /* BMP  */
#define DA601                            76       /* BMP  */
#define DA602                            77       /* BMP  */
#define DARK                             78       /* BMP  */
#define DASH                             79       /* BMP  */
#define dat.exe                          80       /* BMP  */
#define DENY                             81       /* SAMP */
#define DESTROYABLEPAREDE                82       /* BMP  */
#define DESTROYABLEPAREDE2               83       /* BMP  */
#define DIE                              84       /* SAMP */
#define DREAM                            85       /* BMP  */
#define EARTHY                           86       /* BMP  */
#define ENDING1                          87       /* BMP  */
#define ENDING2                          88       /* BMP  */
#define ENDING3                          89       /* BMP  */
#define ENDING4                          90       /* BMP  */
#define ENDING5                          91       /* BMP  */
#define ENDING6                          92       /* BMP  */
#define ENDINGFONT                       93       /* FONT */
#define ERASE                            94       /* BMP  */
#define EWUL_SQUID01                     95       /* BMP  */
#define EWUL_SQUID02                     96       /* BMP  */
#define EWUL_SQUID03                     97       /* BMP  */
#define EWUL_SQUID04                     98       /* BMP  */
#define EWUL_SQUID05                     99       /* BMP  */
#define EWUL_SQUID06                     100      /* BMP  */
#define EWULARMOR1                       101      /* BMP  */
#define EWULARMOR2                       102      /* BMP  */
#define EWULFISH_11                      103      /* BMP  */
#define EWULFISH_12                      104      /* BMP  */
#define EWULFISH_13                      105      /* BMP  */
#define EWULFISH_21                      106      /* BMP  */
#define EWULFISH_22                      107      /* BMP  */
#define EWULFISH_23                      108      /* BMP  */
#define EWULFISH_31                      109      /* BMP  */
#define EWULFISH_32                      110      /* BMP  */
#define EWULFISH_33                      111      /* BMP  */
#define EWULFISH_41                      112      /* BMP  */
#define EWULFISH_42                      113      /* BMP  */
#define EWULFISH_43                      114      /* BMP  */
#define EWULINSETO                       115      /* BMP  */
#define EWULMACHINE01                    116      /* BMP  */
#define EWULMISSILE                      117      /* SAMP */
#define EWULMISSILE01                    118      /* BMP  */
#define EWULOSTRABALLB                   119      /* BMP  */
#define EWULOSTRABALLW                   120      /* BMP  */
#define EWULOSTRAPT1                     121      /* BMP  */
#define EWULOSTRAPT2                     122      /* BMP  */
#define EWULOSTRAPT3                     123      /* BMP  */
#define EWULOSTRAPT4                     124      /* BMP  */
#define EXIT                             125      /* BMP  */
#define FIGHT                            126      /* BMP  */
#define files.dat                        127      /* BMP  */
#define FIRE1                            128      /* BMP  */
#define FIRE2                            129      /* BMP  */
#define FIRE3                            130      /* BMP  */
#define FIRE4                            131      /* BMP  */
#define FIRE5                            132      /* BMP  */
#define FIRE6                            133      /* BMP  */
#define FIRE7                            134      /* BMP  */
#define FIRESLASH                        135      /* SAMP */
#define FIREY                            136      /* BMP  */
#define FIREYFLAME                       137      /* SAMP */
#define FLAMEMET1                        138      /* BMP  */
#define FLAMEMET2                        139      /* BMP  */
#define FLAMEMET3                        140      /* BMP  */
#define FLAMEMET4                        141      /* BMP  */
#define FLAMES01                         142      /* BMP  */
#define FLAMES02                         143      /* BMP  */
#define FLAMES03                         144      /* BMP  */
#define FLAMES04                         145      /* BMP  */
#define FLAMES05                         146      /* BMP  */
#define FLAMES06                         147      /* BMP  */
#define FLAMES07                         148      /* BMP  */
#define FLAMES08                         149      /* BMP  */
#define FLAMES09                         150      /* BMP  */
#define FLAMES11                         151      /* BMP  */
#define FLAMES12                         152      /* BMP  */
#define FLAMES13                         153      /* BMP  */
#define FLAMES14                         154      /* BMP  */
#define FLAMES15                         155      /* BMP  */
#define FLAMES16                         156      /* BMP  */
#define FLAMES17                         157      /* BMP  */
#define FLAMES18                         158      /* BMP  */
#define FLAMES19                         159      /* BMP  */
#define FLAMETHROWER                     160      /* SAMP */
#define FLAMETHROWER1                    161      /* BMP  */
#define FLAMETHROWER2                    162      /* BMP  */
#define FLOAT                            163      /* BMP  */
#define FLOWER                           164      /* BMP  */
#define FLY                              165      /* BMP  */
#define FREEZE                           166      /* BMP  */
#define GHOST01                          167      /* BMP  */
#define GHOST02                          168      /* BMP  */
#define GHOST03                          169      /* BMP  */
#define GHOST04                          170      /* BMP  */
#define GHOSTMASK01                      171      /* BMP  */
#define GHOSTMASK02                      172      /* BMP  */
#define GHOSTMASK03                      173      /* BMP  */
#define GLASS                            174      /* SAMP */
#define GLOW                             175      /* BMP  */
#define GREEN_TURRET                     176      /* BMP  */
#define GUILHOTINA                       177      /* BMP  */
#define HA                               178      /* BMP  */
#define HADOUKEN01                       179      /* BMP  */
#define HADOUKEN02                       180      /* BMP  */
#define HADOUKEN03                       181      /* BMP  */
#define HADOUKEN04                       182      /* BMP  */
#define HADOUKEN05                       183      /* BMP  */
#define HADOUKEN06                       184      /* BMP  */
#define HADOUKEN07                       185      /* BMP  */
#define HADUEX                           186      /* SAMP */
#define ICE01                            187      /* BMP  */
#define ICE02                            188      /* BMP  */
#define ICEANIM                          189      /* SAMP */
#define ICEBLOCK1                        190      /* BMP  */
#define ICEBLOCK2                        191      /* BMP  */
#define ICEDESTROY                       192      /* BMP  */
#define ICEFALL                          193      /* SAMP */
#define ICEHOLDER1                       194      /* BMP  */
#define ICEHOLDER2                       195      /* BMP  */
#define ICEHOLDER3                       196      /* BMP  */
#define ICEHOLDER4                       197      /* BMP  */
#define ICEMET01                         198      /* BMP  */
#define ICEMET02                         199      /* BMP  */
#define ICEMET03                         200      /* BMP  */
#define ICEMET04                         201      /* BMP  */
#define ICENEEDLE01                      202      /* BMP  */
#define ICENEEDLE02                      203      /* BMP  */
#define ICENEEDLE03                      204      /* BMP  */
#define ICENEEDLE04                      205      /* BMP  */
#define ICESPIKE                         206      /* BMP  */
#define ICETOP                           207      /* BMP  */
#define ICETOP2                          208      /* BMP  */
#define ICYATTACK01                      209      /* BMP  */
#define ICYATTACK02                      210      /* BMP  */
#define ICYATTACK03                      211      /* BMP  */
#define ICYATTACK04                      212      /* BMP  */
#define ICYATTACK05                      213      /* BMP  */
#define ICYATTACK06                      214      /* BMP  */
#define ICYSHADOW01                      215      /* BMP  */
#define ICYSHADOW02                      216      /* BMP  */
#define ICYSHADOW03                      217      /* BMP  */
#define ICYSHADOW04                      218      /* BMP  */
#define ICYSIDE01                        219      /* BMP  */
#define ICYSIDE02                        220      /* BMP  */
#define ICYSIDE03                        221      /* BMP  */
#define ICYSIDE04                        222      /* BMP  */
#define ICYUP01                          223      /* BMP  */
#define ICYUP02                          224      /* BMP  */
#define ICYUP03                          225      /* BMP  */
#define ILLUSION                         226      /* BMP  */
#define INIMIGODUMAL                     227      /* BMP  */
#define INTRO                            228      /* MIDI */
#define INTRO0                           229      /* BMP  */
#define INTRO1                           230      /* BMP  */
#define INTRO2                           231      /* BMP  */
#define INTRO3                           232      /* BMP  */
#define INTRO4                           233      /* BMP  */
#define INTRO5                           234      /* BMP  */
#define INTROA                           235      /* BMP  */
#define IRON_DOOR                        236      /* BMP  */
#define JUMP                             237      /* BMP  */
#define LASTBALL1                        238      /* BMP  */
#define LASTBALL2                        239      /* BMP  */
#define LASTBALL3                        240      /* BMP  */
#define LASTBALL4                        241      /* BMP  */
#define LASTBOSS                         242      /* BMP  */
#define LASTS                            243      /* SAMP */
#define LASTSMALL1                       244      /* BMP  */
#define LASTSMALL2                       245      /* BMP  */
#define LASTSMALL3                       246      /* BMP  */
#define LASTSMALL4                       247      /* BMP  */
#define LAVA1                            248      /* BMP  */
#define LAVA2                            249      /* BMP  */
#define LAVA3                            250      /* BMP  */
#define LIBRA                            251      /* BMP  */
#define LIFEBAR                          252      /* BMP  */
#define LIFEMETER                        253      /* BMP  */
#define LIFEMETER2                       254      /* BMP  */
#define LIFEMETERBOSS                    255      /* BMP  */
#define LIGHT                            256      /* BMP  */
#define LITTLE                           257      /* BMP  */
#define LOAD1                            258      /* BMP  */
#define LOAD2                            259      /* BMP  */
#define LOAD3                            260      /* BMP  */
#define LOAD4                            261      /* BMP  */
#define LOCK                             262      /* BMP  */
#define LOOP                             263      /* BMP  */
#define LUZ                              264      /* BMP  */
#define MAINMENU                         265      /* BMP  */
#define MAZE                             266      /* BMP  */
#define MENU                             267      /* BMP  */
#define MENU_EX2                         268      /* BMP  */
#define MENU_FI                          269      /* BMP  */
#define MENU_FI2                         270      /* BMP  */
#define MENU_FR                          271      /* BMP  */
#define MENU_FR2                         272      /* BMP  */
#define MENU_MA2                         273      /* BMP  */
#define MENU_SH                          274      /* BMP  */
#define MENU_SH2                         275      /* BMP  */
#define MENU_TH                          276      /* BMP  */
#define MENU_TH2                         277      /* BMP  */
#define MENU_WA                          278      /* BMP  */
#define MENU_WA2                         279      /* BMP  */
#define MENU_WI                          280      /* BMP  */
#define MENU_WI2                         281      /* BMP  */
#define MENUBACK                         282      /* BMP  */
#define MENUOPTIONS                      283      /* BMP  */
#define MENUWINDOW                       284      /* BMP  */
#define MENUWINDOW2                      285      /* BMP  */
#define MENUWINDY                        286      /* BMP  */
#define MIRROR                           287      /* BMP  */
#define MIST                             288      /* BMP  */
#define MOLA_FELIZ                       289      /* BMP  */
#define MOLA_FELIZ2                      290      /* BMP  */
#define MOVE                             291      /* BMP  */
#define NEWGAME1                         292      /* BMP  */
#define NEWGAME2                         293      /* BMP  */
#define NEWGAME3                         294      /* BMP  */
#define NEWGAME4                         295      /* BMP  */
#define NULO                             296      /* BMP  */
#define OPTIONS                          297      /* BMP  */
#define OPTIONS1                         298      /* BMP  */
#define OPTIONS2                         299      /* BMP  */
#define OPTIONS3                         300      /* BMP  */
#define OPTIONS4                         301      /* BMP  */
#define ORANGE01                         302      /* BMP  */
#define ORANGE02                         303      /* BMP  */
#define ORANGE03                         304      /* BMP  */
#define ORANGE04                         305      /* BMP  */
#define ORANGE05                         306      /* BMP  */
#define ORANGE06                         307      /* BMP  */
#define ORANGE07                         308      /* BMP  */
#define ORANGE08                         309      /* BMP  */
#define ORANGE09                         310      /* BMP  */
#define ORANGEH01                        311      /* BMP  */
#define ORANGEH02                        312      /* BMP  */
#define ORANGEH03                        313      /* BMP  */
#define PAINTING1                        314      /* BMP  */
#define PAINTING2                        315      /* BMP  */
#define PARTICLEDESTROY1                 316      /* BMP  */
#define PARTICLEDESTROY2                 317      /* BMP  */
#define PARTICLES01                      318      /* BMP  */
#define PARTICLES02                      319      /* BMP  */
#define PARTICLES03                      320      /* BMP  */
#define PARTICLES04                      321      /* BMP  */
#define PDIE1                            322      /* BMP  */
#define PDIE2                            323      /* BMP  */
#define PDIE3                            324      /* BMP  */
#define PDIE4                            325      /* BMP  */
#define PDIE5                            326      /* BMP  */
#define PENA                             327      /* BMP  */
#define PENASOUND                        328      /* SAMP */
#define PIRIKITO                         329      /* BMP  */
#define PIRIKITO2                        330      /* BMP  */
#define PIRIKITO3                        331      /* BMP  */
#define PISK1                            332      /* BMP  */
#define PISK2                            333      /* BMP  */
#define PLAYER_MOVING01                  334      /* BMP  */
#define PLAYER_MOVING01A                 335      /* BMP  */
#define PLAYER_MOVING01B                 336      /* BMP  */
#define PLAYER_MOVING01C                 337      /* BMP  */
#define PLAYER_MOVING01D                 338      /* BMP  */
#define PLAYER_MOVING01E                 339      /* BMP  */
#define PLAYER_MOVING01F                 340      /* BMP  */
#define PLAYER_MOVING02                  341      /* BMP  */
#define PLAYER_MOVING02A                 342      /* BMP  */
#define PLAYER_MOVING02B                 343      /* BMP  */
#define PLAYER_MOVING02C                 344      /* BMP  */
#define PLAYER_MOVING02D                 345      /* BMP  */
#define PLAYER_MOVING02E                 346      /* BMP  */
#define PLAYER_MOVING02F                 347      /* BMP  */
#define PLAYER_MOVING03                  348      /* BMP  */
#define PLAYER_MOVING03A                 349      /* BMP  */
#define PLAYER_MOVING03B                 350      /* BMP  */
#define PLAYER_MOVING03C                 351      /* BMP  */
#define PLAYER_MOVING03D                 352      /* BMP  */
#define PLAYER_MOVING03E                 353      /* BMP  */
#define PLAYER_MOVING03F                 354      /* BMP  */
#define PLAYER_MOVING04                  355      /* BMP  */
#define PLAYER_MOVING04A                 356      /* BMP  */
#define PLAYER_MOVING04B                 357      /* BMP  */
#define PLAYER_MOVING04C                 358      /* BMP  */
#define PLAYER_MOVING04D                 359      /* BMP  */
#define PLAYER_MOVING04E                 360      /* BMP  */
#define PLAYER_MOVING04F                 361      /* BMP  */
#define PLAYER_MOVING05                  362      /* BMP  */
#define PLAYER_MOVING05A                 363      /* BMP  */
#define PLAYER_MOVING05B                 364      /* BMP  */
#define PLAYER_MOVING05C                 365      /* BMP  */
#define PLAYER_MOVING05D                 366      /* BMP  */
#define PLAYER_MOVING05E                 367      /* BMP  */
#define PLAYER_MOVING05F                 368      /* BMP  */
#define PLAYER_MOVING12                  369      /* BMP  */
#define PLAYER_MOVING12A                 370      /* BMP  */
#define PLAYER_MOVING12B                 371      /* BMP  */
#define PLAYER_MOVING12C                 372      /* BMP  */
#define PLAYER_MOVING12D                 373      /* BMP  */
#define PLAYER_MOVING12E                 374      /* BMP  */
#define PLAYER_MOVING12F                 375      /* BMP  */
#define PLAYER_MOVING22                  376      /* BMP  */
#define PLAYER_MOVING22A                 377      /* BMP  */
#define PLAYER_MOVING22B                 378      /* BMP  */
#define PLAYER_MOVING22C                 379      /* BMP  */
#define PLAYER_MOVING22D                 380      /* BMP  */
#define PLAYER_MOVING22E                 381      /* BMP  */
#define PLAYER_MOVING22F                 382      /* BMP  */
#define PLAYER_MOVING32                  383      /* BMP  */
#define PLAYER_MOVING32A                 384      /* BMP  */
#define PLAYER_MOVING32B                 385      /* BMP  */
#define PLAYER_MOVING32C                 386      /* BMP  */
#define PLAYER_MOVING32D                 387      /* BMP  */
#define PLAYER_MOVING32E                 388      /* BMP  */
#define PLAYER_MOVING32F                 389      /* BMP  */
#define PLAYER_MOVING42                  390      /* BMP  */
#define PLAYER_MOVING42A                 391      /* BMP  */
#define PLAYER_MOVING42B                 392      /* BMP  */
#define PLAYER_MOVING42C                 393      /* BMP  */
#define PLAYER_MOVING42D                 394      /* BMP  */
#define PLAYER_MOVING42E                 395      /* BMP  */
#define PLAYER_MOVING42F                 396      /* BMP  */
#define PLAYER_MOVING52                  397      /* BMP  */
#define PLAYER_MOVING52A                 398      /* BMP  */
#define PLAYER_MOVING52B                 399      /* BMP  */
#define PLAYER_MOVING52C                 400      /* BMP  */
#define PLAYER_MOVING52D                 401      /* BMP  */
#define PLAYER_MOVING52E                 402      /* BMP  */
#define PLAYER_MOVING52F                 403      /* BMP  */
#define PLAYERD                          404      /* BMP  */
#define PORTA1                           405      /* BMP  */
#define PORTA2                           406      /* BMP  */
#define PORTAL1                          407      /* BMP  */
#define PORTAL2                          408      /* BMP  */
#define PORTAL3                          409      /* BMP  */
#define PORTAL4                          410      /* BMP  */
#define PORTAL5                          411      /* BMP  */
#define PORTAL6                          412      /* BMP  */
#define POSTE                            413      /* BMP  */
#define POWER                            414      /* BMP  */
#define PPP1                             415      /* BMP  */
#define PPP2                             416      /* BMP  */
#define PPP3                             417      /* BMP  */
#define PPP4                             418      /* BMP  */
#define PPP5                             419      /* BMP  */
#define PPP6                             420      /* BMP  */
#define PUMPKIN01                        421      /* BMP  */
#define PUMPKIN02                        422      /* BMP  */
#define PUMPKIN03                        423      /* BMP  */
#define PUMPKIN04                        424      /* BMP  */
#define PUMPKIN05                        425      /* BMP  */
#define QUICAR                           426      /* SAMP */
#define QUIT1                            427      /* BMP  */
#define QUIT2                            428      /* BMP  */
#define QUIT3                            429      /* BMP  */
#define QUIT4                            430      /* BMP  */
#define QUITGAME                         431      /* BMP  */
#define RAIN                             432      /* BMP  */
#define READY                            433      /* BMP  */
#define RECOVERY_L                       434      /* BMP  */
#define RECOVERY_M                       435      /* BMP  */
#define RECOVERY_S                       436      /* BMP  */
#define RECUPERATOR                      437      /* SAMP */
#define RECUPERATORS                     438      /* SAMP */
#define RED_TANK                         439      /* BMP  */
#define RED_TANK_2                       440      /* BMP  */
#define RED_TANK_3                       441      /* BMP  */
#define REDBALL01                        442      /* BMP  */
#define REDBALL02                        443      /* BMP  */
#define REDBALL03                        444      /* BMP  */
#define REDBALL04                        445      /* BMP  */
#define REDBALL05                        446      /* BMP  */
#define RESETTI                          447      /* BMP  */
#define RETURN                           448      /* BMP  */
#define ROAR                             449      /* SAMP */
#define ROAR2                            450      /* SAMP */
#define SAND                             451      /* BMP  */
#define SANDMORRO1                       452      /* BMP  */
#define SANDMORRO2                       453      /* BMP  */
#define SANDMORRO3                       454      /* BMP  */
#define SANDMORRO4                       455      /* BMP  */
#define SANDS                            456      /* SAMP */
#define SAVEGAME                         457      /* BMP  */
#define SC01                             458      /* BMP  */
#define SC02                             459      /* BMP  */
#define SC03                             460      /* BMP  */
#define SC04                             461      /* BMP  */
#define SC05                             462      /* BMP  */
#define SC06                             463      /* BMP  */
#define SC07                             464      /* BMP  */
#define SC08                             465      /* BMP  */
#define SC09                             466      /* BMP  */
#define SC10                             467      /* BMP  */
#define SC11                             468      /* BMP  */
#define SC12                             469      /* BMP  */
#define SCALED01                         470      /* BMP  */
#define SCALED02                         471      /* BMP  */
#define SCALED03                         472      /* BMP  */
#define SCALED04                         473      /* BMP  */
#define SCALEDCUT01                      474      /* BMP  */
#define SCALEDCUT02                      475      /* BMP  */
#define SCALEDFIRE01                     476      /* BMP  */
#define SCALEDFIRE02                     477      /* BMP  */
#define SCALEDFIRE03                     478      /* BMP  */
#define SEAHORSE1                        479      /* BMP  */
#define SEAHORSE2                        480      /* BMP  */
#define SEAHORSE3                        481      /* BMP  */
#define SELECT                           482      /* BMP  */
#define SELECT2                          483      /* BMP  */
#define SETA                             484      /* BMP  */
#define SETA2                            485      /* BMP  */
#define SFIRE1                           486      /* BMP  */
#define SFIRE2                           487      /* BMP  */
#define SFIRE3                           488      /* BMP  */
#define SFIRE4                           489      /* BMP  */
#define SFIRE5                           490      /* BMP  */
#define SFIRE6                           491      /* BMP  */
#define SFIRE7                           492      /* BMP  */
#define SHADOW                           493      /* BMP  */
#define SHADOW01                         494      /* BMP  */
#define SHADOW02                         495      /* BMP  */
#define SHADOW03                         496      /* BMP  */
#define SHADOWBALL                       497      /* BMP  */
#define SHADOWSHOT                       498      /* BMP  */
#define SHADOWSPIKE                      499      /* BMP  */
#define SHIELD                           500      /* BMP  */
#define SHOCKER01                        501      /* BMP  */
#define SHOCKER02                        502      /* BMP  */
#define SHOCKER03                        503      /* BMP  */
#define SHOCKER04                        504      /* BMP  */
#define SHOCKER05                        505      /* BMP  */
#define SHOCKING01                       506      /* BMP  */
#define SHOCKING02                       507      /* BMP  */
#define SHOCKING03                       508      /* BMP  */
#define SHOCKING04                       509      /* BMP  */
#define SHOCKING05                       510      /* BMP  */
#define SHOT                             511      /* BMP  */
#define SHOT_0_1                         512      /* BMP  */
#define SHOT_0_2                         513      /* BMP  */
#define SHOT_0_3                         514      /* BMP  */
#define SHOT_13_1                        515      /* BMP  */
#define SHOT_13_2                        516      /* BMP  */
#define SHOT_13_3                        517      /* BMP  */
#define SILENT                           518      /* BMP  */
#define SLASH01                          519      /* BMP  */
#define SLASH02                          520      /* BMP  */
#define SLEEP                            521      /* BMP  */
#define SNOW                             522      /* BMP  */
#define SONG                             523      /* BMP  */
#define SPARKLE                          524      /* SAMP */
#define SPARKLE1                         525      /* BMP  */
#define SPARKLE2                         526      /* BMP  */
#define SPARKLE3                         527      /* BMP  */
#define SPARKLE4                         528      /* BMP  */
#define SPLAASH                          529      /* SAMP */
#define SPLASH                           530      /* SAMP */
#define SPLASH1                          531      /* BMP  */
#define SPLASH2                          532      /* BMP  */
#define SPLASH3                          533      /* BMP  */
#define STAFFA                           534      /* BMP  */
#define STAFFB                           535      /* BMP  */
#define STAFFC                           536      /* BMP  */
#define STAFFD                           537      /* BMP  */
#define STAFFE                           538      /* BMP  */
#define STAFFF                           539      /* BMP  */
#define STAFFG                           540      /* BMP  */
#define STAFFH                           541      /* BMP  */
#define STAFFI                           542      /* BMP  */
#define STAFFJ                           543      /* BMP  */
#define STAFFK                           544      /* BMP  */
#define STAFFL                           545      /* BMP  */
#define STAFFM                           546      /* BMP  */
#define STAFFN                           547      /* BMP  */
#define STAFFO                           548      /* BMP  */
#define STAFFP                           549      /* BMP  */
#define STAFFQ                           550      /* BMP  */
#define STAFFR                           551      /* BMP  */
#define STAFFS                           552      /* BMP  */
#define STAFFT                           553      /* BMP  */
#define STAFFU                           554      /* BMP  */
#define STAFFV                           555      /* BMP  */
#define STAFFW                           556      /* BMP  */
#define STAFFX                           557      /* BMP  */
#define STAFFY                           558      /* BMP  */
#define STAFFZ                           559      /* BMP  */
#define STAGEFIRE                        560      /* BMP  */
#define STAGEFIRE2                       561      /* BMP  */
#define STAGEICE                         562      /* BMP  */
#define STAGEICE2                        563      /* BMP  */
#define STAGESHADOW                      564      /* BMP  */
#define STAGESHADOW2                     565      /* BMP  */
#define STAGETHUNDER                     566      /* BMP  */
#define STAGETHUNDER2                    567      /* BMP  */
#define STAGEWATER                       568      /* BMP  */
#define STAGEWATER2                      569      /* BMP  */
#define STAGEWIND                        570      /* BMP  */
#define STAGEWIND2                       571      /* BMP  */
#define START01                          572      /* BMP  */
#define START02                          573      /* BMP  */
#define START03                          574      /* BMP  */
#define START04                          575      /* BMP  */
#define START05                          576      /* BMP  */
#define START06                          577      /* BMP  */
#define STORM                            578      /* BMP  */
#define SWEET                            579      /* BMP  */
#define SWORD                            580      /* BMP  */
#define TEXTURES01                       581      /* BMP  */
#define TEXTURES02                       582      /* BMP  */
#define TEXTURES04                       583      /* BMP  */
#define TEXTURES05                       584      /* BMP  */
#define TEXTURES06                       585      /* BMP  */
#define TEXTURES07                       586      /* BMP  */
#define TEXTURES08                       587      /* BMP  */
#define TEXTURES09                       588      /* BMP  */
#define THANKS                           589      /* BMP  */
#define THE                              590      /* BMP  */
#define THEEND                           591      /* BMP  */
#define THROUGH                          592      /* BMP  */
#define THUNDER                          593      /* BMP  */
#define THUNDER01                        594      /* BMP  */
#define THUNDER02                        595      /* BMP  */
#define THUNDER03                        596      /* BMP  */
#define THUNDER04                        597      /* BMP  */
#define THUNDER05                        598      /* BMP  */
#define THUNDER_SHOT01                   599      /* BMP  */
#define THUNDER_SHOT02                   600      /* BMP  */
#define THUNDER_SHOT03                   601      /* BMP  */
#define THUNDERRAIO01                    602      /* BMP  */
#define THUNDERRAIO02                    603      /* BMP  */
#define THUNDERRAIO03                    604      /* BMP  */
#define THUNDERRAIO04                    605      /* BMP  */
#define THUNDERSOUND                     606      /* SAMP */
#define THUNDERUP01                      607      /* BMP  */
#define THUNDERUP02                      608      /* BMP  */
#define THUNDERUP03                      609      /* BMP  */
#define THUNDERUP04                      610      /* BMP  */
#define TIME                             611      /* BMP  */
#define TIRO1                            612      /* SAMP */
#define TIRO2                            613      /* SAMP */
#define TIRO3                            614      /* SAMP */
#define TIRO4                            615      /* SAMP */
#define TIRO5                            616      /* SAMP */
#define TIRO6                            617      /* SAMP */
#define TIRO7                            618      /* SAMP */
#define TOLETED_1                        619      /* BMP  */
#define TOLETED_2                        620      /* BMP  */
#define TOLETED_3                        621      /* BMP  */
#define TURRET                           622      /* SAMP */
#define TURRET_SHOT                      623      /* BMP  */
#define TURTLE                           624      /* BMP  */
#define TURTLE_ENTER1                    625      /* BMP  */
#define TURTLE_ENTER2                    626      /* BMP  */
#define TURTLE_ENTER3                    627      /* BMP  */
#define TURTLE_OPEN1                     628      /* BMP  */
#define TURTLE_OPEN2                     629      /* BMP  */
#define TURTLEDASH                       630      /* SAMP */
#define TURTLEJATO                       631      /* SAMP */
#define TWIN                             632      /* BMP  */
#define V0                               633      /* BMP  */
#define V1                               634      /* BMP  */
#define V2                               635      /* BMP  */
#define V3                               636      /* BMP  */
#define V4                               637      /* BMP  */
#define V5                               638      /* BMP  */
#define V6                               639      /* BMP  */
#define V7                               640      /* BMP  */
#define V8                               641      /* BMP  */
#define V9                               642      /* BMP  */
#define VIDA                             643      /* BMP  */
#define VIDA1                            644      /* BMP  */
#define VIDAA                            645      /* BMP  */
#define VIDAA1                           646      /* BMP  */
#define VIDAB                            647      /* BMP  */
#define VIDAB1                           648      /* BMP  */
#define VIDAC                            649      /* BMP  */
#define VIDAC1                           650      /* BMP  */
#define VIDAD                            651      /* BMP  */
#define VIDAD1                           652      /* BMP  */
#define VIDAE                            653      /* BMP  */
#define VIDAE1                           654      /* BMP  */
#define VIDAF                            655      /* BMP  */
#define VIDAF1                           656      /* BMP  */
#define VIDAZ                            657      /* BMP  */
#define VOICE                            658      /* BMP  */
#define WALLMAGIC                        659      /* BMP  */
#define WALLTURRET                       660      /* BMP  */
#define WALLTURRET2                      661      /* BMP  */
#define WATER_FIM1                       662      /* BMP  */
#define WATER_FIM2                       663      /* BMP  */
#define WATER_MEIO1                      664      /* BMP  */
#define WATER_MEIO2                      665      /* BMP  */
#define WATER_PONTA1                     666      /* BMP  */
#define WATER_PONTA2                     667      /* BMP  */
#define WATERSHOT                        668      /* BMP  */
#define WATERSHOTHIT1                    669      /* BMP  */
#define WATERSHOTHIT2                    670      /* BMP  */
#define WATERSHOTHIT3                    671      /* BMP  */
#define WATERSHOTHIT4                    672      /* BMP  */
#define WATERSHOTHIT5                    673      /* BMP  */
#define WATERSHOTHIT6                    674      /* BMP  */
#define WATERSHOTHIT7                    675      /* BMP  */
#define WATERSHOTHIT8                    676      /* BMP  */
#define WATERSHOTHIT9                    677      /* BMP  */
#define WATERSHOTSMALL                   678      /* BMP  */
#define WATERY                           679      /* BMP  */
#define WAVE                             680      /* BMP  */
#define WIND_SHOT01                      681      /* BMP  */
#define WIND_SHOT02                      682      /* BMP  */
#define WIND_SHOT03                      683      /* BMP  */
#define WINDMILL0                        684      /* BMP  */
#define WINDMILL1                        685      /* BMP  */
#define WINDOW                           686      /* BMP  */
#define WINDY                            687      /* BMP  */
#define WINDY01                          688      /* BMP  */
#define WINDY02                          689      /* BMP  */
#define WINDYDASH                        690      /* SAMP */
#define WOOD                             691      /* BMP  */
#define WTS                              692      /* SAMP */
#define WTSHOT01                         693      /* BMP  */
#define WTSHOT02                         694      /* BMP  */
#define WTSHOT03                         695      /* BMP  */
#define YELLOW_TOSKO_SHOT                696      /* BMP  */
#define ZOCK01                           697      /* BMP  */
#define ZOCK02                           698      /* BMP  */
#define ZOCK03                           699      /* BMP  */
#define ZOCK04                           700      /* BMP  */

