void increment_speed_counter();
void load_map(char mapnumber);
void setup_game();
void initiate_level(int mapnumber);
void initialize_wall(int framex, int framey, int type, int w, int h, int x, int y);
void initialize_sprite(int type, int x_position, int y_position,  int direction, int time);
void animation(int sprite_number);
void die();
void destroysprite(int spritee);
void destroysprite();
void destroywall();
void sprite_update(int spriten);
int check_colision(int sprite_number, int loop, int sop);
int inpl(int x);
void sprite_colision(int sprite_number, int type);
void damage(int howmuch);
void player_colision();
void enemy_ai(int type, int sprite_number);
void input();
void move_player(float x_amount, float y_amount);
void draw();
void set_dvalues(int number);
void callevent(int event_number);
void run_scripts();
void main_menu();
void draw_menu();
void cselect();
void draw_cselect();
void move_to_end();
void myoptions();
void draw_options();
void set_controls();
void gamemenu();
void drawgamemenu();
void savegame();
int loadgame();
void myend();
void drawend();

typedef struct{
	float timer;
	int imune;
	int width, height;
	int frame;
	char animation_timer;
	char direction;
	int current_weapon;
	char on_ground;
	char in_water;
	char letter_order;
	int score;
	char hp;
	float x_position, y_position;
	float x_speed, y_speed;
	char skin;
	char move;
	char shots;
	char shooting;
	char cards[52];
	int shine;
	int key_up, key_down, key_right, key_left, key_fire, key_jump, key_weapon1, key_weapon2, key_menu, key_quit;
    int vidas;
    char hpmax;
} PLAYER;

typedef struct{
	char active;
	int type;
	int timer;
	char animation_state;
	int width, height;
	int action_state;
	int frame;
	float hit_points_left;
	float x_position, y_position;
	float x_speed, y_speed;
	int direction;
	unsigned char rotate_factor;
	int biba;
	int strength;
} SPRITE;

typedef struct {
    char active;
    int type;
	int width, height;
	float x_position, y_position;
} WALL;

typedef struct {
    short int width;
    short int height;
    short int limitleft;
    short int limitright;
    short int limitup;
    short int limitdown;
    char type;
    char number;
   	int startingpointx, startingpointy;
   	int water_position;
} MAPS;

COLOR_MAP global_trans_table;

PLAYER player;
SPRITE sprites[100];
WALL walls[10000];
MAPS Map;

BITMAP* scenario;
BITMAP* buffer;
BITMAP* title;
BITMAP* bakg;
BITMAP* background;
BITMAP* foreground;
DATAFILE *mydatafile = NULL;
FILE *fmap;
ofstream fsav;
ifstream fload;
MIDI* title_music;
MIDI* select_music;
MIDI* stage_music;
ofstream myfile;
int recordinging;

unsigned char **map;
char txt[80];
char txt2[80];
char mensagem[40];
char checker;
unsigned char jump_key_state = 0;
int fire_key = 0;
float bolas[12][2];
int number_of_walls;
int dieanimation;
int texture;

int screenx = 0, screeny = 0;
int number_of_sprites = 0;
volatile long speed_counter = 0;
volatile int last_fps;
volatile int frame_counter;
int actual_cycle;
char current_level = 0;
char desired_weapon = 0;
char w84go = 0;
char i_like_pizza = 0;
int myrandnumber;
int bibinhalinda, bibinhafeia, dead;
int limpation;
int input_locked, screen_locked;
int bframe;
int weaponlock;
char vglvfs;
char stopall;
char movingscreen;
int looper;
int doorrecord = -1;
int event_organizer;
int call_event;
int bosslife = -1;
char menu;
int key_rest;
char bossfight;
int light_level;
char flash_screen;
int aguaa;
char mainmenu;
char key_enter_rest = 1;
char key_f_rest = 1;
int pisca;
int starting, starting2, finishing;
char howtoend, characterscreen;
int music_volume_set = 1;
int sound_volume_set = 255;
char gamemenustat;
char timetoquit;
char menupos;
int menuposx, menuposy;
char next_level;
char paulaumfromhell;
int create_bubbles;
char gamestartmusic;
int osutatakaefadeout;
int something, something2;
char lastageportal[6];
char lastageboss;
int lastagedoor;
int lastageblack;
int sparkmandril;
int itsover;
int yeahyeah;
BITMAP* endtext;
int endtextx, endtextw;
