# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = Main.o $(RES)
LINKOBJ  = Main.o $(RES)
LIBS =  -L"C:/DEV-CPP/lib" -mwindows -lalleg_s -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -ldinput -lddraw -ldxguid -lwinmm -ldsound 
INCS =  -I"C:/DEV-CPP/include" 
CXXINCS =  -I"C:/DEV-CPP/lib/gcc/mingw32/3.4.2/include"  -I"C:/DEV-CPP/include/c++/3.4.2/backward"  -I"C:/DEV-CPP/include/c++/3.4.2/mingw32"  -I"C:/DEV-CPP/include/c++/3.4.2"  -I"C:/DEV-CPP/include" 
BIN  = Joguito.exe
CXXFLAGS = $(CXXINCS) -DALLEGRO_STATICLINK 
CFLAGS = $(INCS) -DALLEGRO_STATICLINK 
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Joguito.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Joguito.exe" $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)
